/*
 * Created by Michael Carrara <michael.carrara@breadwallet.com> on 10/1/19.
 * Copyright (c) 2019 Breadwinner AG.  All right reserved.
 *
 * See the LICENSE file at the project root for license information.
 * See the CONTRIBUTORS file at the project root for a list of contributors.
 */
package com.breadwallet.corecrypto;

import com.breadwallet.crypto.CryptoApi;
import com.breadwallet.crypto.Network;
import com.breadwallet.crypto.System;
import com.breadwallet.crypto.Transfer;
import com.breadwallet.crypto.Wallet;
import com.breadwallet.crypto.WalletManager;
import com.breadwallet.crypto.blockchaindb.BlockchainDb;
import com.breadwallet.crypto.events.network.NetworkEvent;
import com.breadwallet.crypto.events.system.DefaultSystemListener;
import com.breadwallet.crypto.events.system.SystemEvent;
import com.breadwallet.crypto.events.system.SystemListener;
import com.breadwallet.crypto.events.system.SystemManagerAddedEvent;
import com.breadwallet.crypto.events.system.SystemNetworkAddedEvent;
import com.breadwallet.crypto.events.transfer.TranferEvent;
import com.breadwallet.crypto.events.wallet.WalletEvent;
import com.breadwallet.crypto.events.walletmanager.WalletManagerEvent;
import com.breadwallet.crypto.events.walletmanager.WalletManagerWalletAddedEvent;
import com.google.common.base.Optional;
import com.google.common.io.Files;
import com.google.common.util.concurrent.Uninterruptibles;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import okhttp3.OkHttpClient;

/* package */
class HelpersAIT {

    // Filesystem

    /* package */
    static File generateCoreDataDir() {
        return Files.createTempDir();
    }

    /* package */
    static boolean createOrOverwriteDirectory(File file) {
        return deleteFile(file) && file.mkdirs();
    }

    /* package */
    static boolean deleteFile(File file) {
        if (file.isDirectory()) {
            for (File child : file.listFiles()) {
                if (!deleteFile(child)) {
                    return false;
                }
            }
        }
        return file.delete();
    }

    // Module

    /* package */
    static void registerCryptoApiProvider() {
        try {
            CryptoApi.initialize(CryptoApiProvider.getInstance());
        }  catch (IllegalStateException e) {
            // already initialized, ignore
        }
    }

    // System

    /* package */
    static System createAndConfigureSystem(File dataDir) {
        String storagePath = dataDir.getAbsolutePath();
        Account account = HelpersAIT.createDefaultAccount();
        SystemListener listener = new DefaultSystemListener() {};
        BlockchainDb query = HelpersAIT.createDefaultBlockchainDbWithToken();
        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
        com.breadwallet.corecrypto.System system = com.breadwallet.corecrypto.System.create(executor, listener, account, false, storagePath, query);

        system.configure(Collections.emptyList());
        Uninterruptibles.sleepUninterruptibly(5, TimeUnit.SECONDS);

        return system;
    }

    /* package */
    static System createAndConfigureSystemWithListener(File dataDir, SystemListener listener) {
        String storagePath = dataDir.getAbsolutePath();
        Account account = HelpersAIT.createDefaultAccount();
        BlockchainDb query = HelpersAIT.createDefaultBlockchainDbWithToken();
        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
        com.breadwallet.corecrypto.System system = com.breadwallet.corecrypto.System.create(executor, listener, account, false, storagePath, query);

        system.configure(Collections.emptyList());
        Uninterruptibles.sleepUninterruptibly(5, TimeUnit.SECONDS);

        return system;
    }

    /* package */
    static System createAndConfigureSystemWithBlockchainDbAndCurrencies(File dataDir, BlockchainDb query, List<com.breadwallet.crypto.blockchaindb.models.bdb.Currency> currencies) {
        String storagePath = dataDir.getAbsolutePath();
        Account account = HelpersAIT.createDefaultAccount();
        SystemListener listener = new DefaultSystemListener() {};
        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
        com.breadwallet.corecrypto.System system = com.breadwallet.corecrypto.System.create(executor, listener, account, false, storagePath, query);

        system.configure(currencies);
        Uninterruptibles.sleepUninterruptibly(5, TimeUnit.SECONDS);

        return system;
    }

    /* package */
    static Optional<Network> getNetworkByCurrencyCode(Collection<Network> networks, String code) {
        Network out = null;
        for (Network network: networks) {
            if (code.equals(network.getCurrency().getCode().toLowerCase())) {
                out = network;
                break;
            }
        }
        return Optional.fromNullable(out);
    }

    /* package */
    static Optional<WalletManager> getManagerByCode(Collection<WalletManager> managers, String code) {
        WalletManager out = null;
        for (WalletManager manager: managers) {
            if (code.equals(manager.getCurrency().getCode().toLowerCase())) {
                out = manager;
                break;
            }
        }
        return Optional.fromNullable(out);
    }

    /* package */
    static Optional<Wallet> getWalletByCode(Collection<Wallet> wallets, String code) {
        Wallet out = null;
        for (Wallet wallet: wallets) {
            if (code.equals(wallet.getCurrency().getCode().toLowerCase())) {
                out = wallet;
                break;
            }
        }
        return Optional.fromNullable(out);
    }

    // Accounts

    private static final byte[] DEFAULT_ACCOUNT_KEY = "ginger settle marine tissue robot crane night number ramp coast roast critic"
            .getBytes(StandardCharsets.UTF_8);

    private static final Date DEFAULT_ACCOUNT_TIMESTAMP = new Date(TimeUnit.SECONDS.toMillis(1507328506));

    private static final String DEFAULT_ACCOUNT_UIDS = "5766b9fa-e9aa-4b6d-9b77-b5f1136e5e96";

    /* package */
    static Account createDefaultAccount() {
        return Account.createFromPhrase(DEFAULT_ACCOUNT_KEY, DEFAULT_ACCOUNT_TIMESTAMP, DEFAULT_ACCOUNT_UIDS);
    }

    // BlockchainDB

    /* package */
    static final OkHttpClient DEFAULT_HTTP_CLIENT = new OkHttpClient();

    private static String DEFAULT_TOKEN = "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9." +
            "eyJzdWIiOiJjNzQ5NTA2ZS02MWUzLTRjM2UtYWNiNS00OTY5NTM2ZmRhMTAiLCJpYXQiOjE1N" +
            "zI1NDY1MDAuODg3LCJleHAiOjE4ODAxMzA1MDAuODg3LCJicmQ6Y3QiOiJ1c3IiLCJicmQ6Y2" +
            "xpIjoiZGViNjNlMjgtMDM0NS00OGY2LTlkMTctY2U4MGNiZDYxN2NiIn0." +
            "460_GdAWbONxqOhWL5TEbQ7uEZi3fSNrl0E_Zg7MAg570CVcgO7rSMJvAPwaQtvIx1XFK_QZjcoNULmB8EtOdg";

    /* package */
    static BlockchainDb createDefaultBlockchainDbWithToken() {
        return BlockchainDb.createForTest(DEFAULT_HTTP_CLIENT, DEFAULT_TOKEN);
    }

    /* package */
    static BlockchainDb createDefaultBlockchainDbWithoutToken() {
        return new BlockchainDb(DEFAULT_HTTP_CLIENT);
    }

    // Listeners

    /* package */
    static RecordingSystemListener createRecordingListener() {
        return new RecordingSystemListener();
    }

    private HelpersAIT() {}

    public static class RecordingSystemListener implements SystemListener {

        private static class CryptoEvent {

            private final System system;
            private final Network network;
            private final WalletManager manager;
            private final Wallet wallet;
            private final Transfer transfer;
            private final Object event;

            private CryptoEvent(System system, SystemEvent event) {
                this.system = system;
                this.network = null;
                this.manager = null;
                this.wallet = null;
                this.transfer = null;
                this.event = event;
            }

            private CryptoEvent(System system, Network network, NetworkEvent event) {
                this.system = system;
                this.network = network;
                this.manager = null;
                this.wallet = null;
                this.transfer = null;
                this.event = event;
            }

            private CryptoEvent(System system, WalletManager manager, WalletManagerEvent event) {
                this.system = system;
                this.network = null;
                this.manager = manager;
                this.wallet = null;
                this.transfer = null;
                this.event = event;
            }

            private CryptoEvent(System system, WalletManager manager, Wallet wallet, WalletEvent event) {
                this.system = system;
                this.network = null;
                this.manager = manager;
                this.wallet = wallet;
                this.transfer = null;
                this.event = event;
            }

            private CryptoEvent(System system, WalletManager manager, Wallet wallet, Transfer transfer, TranferEvent event) {
                this.system = system;
                this.network = null;
                this.manager = manager;
                this.wallet = wallet;
                this.transfer = transfer;
                this.event = event;
            }
        }

        private final List<CryptoEvent> events = new CopyOnWriteArrayList<>();

        @Override
        public void handleSystemEvent(System system, SystemEvent event) {
            events.add(new CryptoEvent(system, event));
        }

        @Override
        public void handleNetworkEvent(System system, Network network, NetworkEvent event) {
            events.add(new CryptoEvent(system, network, event));
        }

        @Override
        public void handleManagerEvent(System system, WalletManager manager, WalletManagerEvent event) {
            events.add(new CryptoEvent(system, manager, event));
        }

        @Override
        public void handleWalletEvent(System system, WalletManager manager, Wallet wallet, WalletEvent event) {
            events.add(new CryptoEvent(system, manager, wallet, event));
        }

        @Override
        public void handleTransferEvent(System system, WalletManager manager, Wallet wallet, Transfer transfer,
                                        TranferEvent event) {
            events.add(new CryptoEvent(system, manager, wallet, transfer, event));
        }

        /* package */
        Collection<Network> getAddedNetworks() {
            Set<Network> networks = new HashSet<>();
            for (CryptoEvent event: events) {
                if (event.event instanceof SystemNetworkAddedEvent) {
                    SystemNetworkAddedEvent e = (SystemNetworkAddedEvent) event.event;
                    networks.add(e.getNetwork());
                }
            }
            return networks;
        }

        /* package */
        Collection<WalletManager> getAddedManagers() {
            Set<WalletManager> managers = new HashSet<>();
            for (CryptoEvent event: events) {
                if (event.event instanceof SystemManagerAddedEvent) {
                    SystemManagerAddedEvent e = (SystemManagerAddedEvent) event.event;
                    managers.add(e.getWalletManager());
                }
            }
            return managers;
        }

        /* package */
        Collection<Wallet> getAddedWallets() {
            Set<Wallet> managers = new HashSet<>();
            for (CryptoEvent event: events) {
                if (event.event instanceof WalletManagerWalletAddedEvent) {
                    WalletManagerWalletAddedEvent e = (WalletManagerWalletAddedEvent) event.event;
                    managers.add(e.getWallet());
                }
            }
            return managers;
        }
    }

    /* package */
    static List<String> BIP39_WORDS_EN = Arrays.asList("abandon",
            "ability",
            "able",
            "about",
            "above",
            "absent",
            "absorb",
            "abstract",
            "absurd",
            "abuse",
            "access",
            "accident",
            "account",
            "accuse",
            "achieve",
            "acid",
            "acoustic",
            "acquire",
            "across",
            "act",
            "action",
            "actor",
            "actress",
            "actual",
            "adapt",
            "add",
            "addict",
            "address",
            "adjust",
            "admit",
            "adult",
            "advance",
            "advice",
            "aerobic",
            "affair",
            "afford",
            "afraid",
            "again",
            "age",
            "agent",
            "agree",
            "ahead",
            "aim",
            "air",
            "airport",
            "aisle",
            "alarm",
            "album",
            "alcohol",
            "alert",
            "alien",
            "all",
            "alley",
            "allow",
            "almost",
            "alone",
            "alpha",
            "already",
            "also",
            "alter",
            "always",
            "amateur",
            "amazing",
            "among",
            "amount",
            "amused",
            "analyst",
            "anchor",
            "ancient",
            "anger",
            "angle",
            "angry",
            "animal",
            "ankle",
            "announce",
            "annual",
            "another",
            "answer",
            "antenna",
            "antique",
            "anxiety",
            "any",
            "apart",
            "apology",
            "appear",
            "apple",
            "approve",
            "april",
            "arch",
            "arctic",
            "area",
            "arena",
            "argue",
            "arm",
            "armed",
            "armor",
            "army",
            "around",
            "arrange",
            "arrest",
            "arrive",
            "arrow",
            "art",
            "artefact",
            "artist",
            "artwork",
            "ask",
            "aspect",
            "assault",
            "asset",
            "assist",
            "assume",
            "asthma",
            "athlete",
            "atom",
            "attack",
            "attend",
            "attitude",
            "attract",
            "auction",
            "audit",
            "august",
            "aunt",
            "author",
            "auto",
            "autumn",
            "average",
            "avocado",
            "avoid",
            "awake",
            "aware",
            "away",
            "awesome",
            "awful",
            "awkward",
            "axis",
            "baby",
            "bachelor",
            "bacon",
            "badge",
            "bag",
            "balance",
            "balcony",
            "ball",
            "bamboo",
            "banana",
            "banner",
            "bar",
            "barely",
            "bargain",
            "barrel",
            "base",
            "basic",
            "basket",
            "battle",
            "beach",
            "bean",
            "beauty",
            "because",
            "become",
            "beef",
            "before",
            "begin",
            "behave",
            "behind",
            "believe",
            "below",
            "belt",
            "bench",
            "benefit",
            "best",
            "betray",
            "better",
            "between",
            "beyond",
            "bicycle",
            "bid",
            "bike",
            "bind",
            "biology",
            "bird",
            "birth",
            "bitter",
            "black",
            "blade",
            "blame",
            "blanket",
            "blast",
            "bleak",
            "bless",
            "blind",
            "blood",
            "blossom",
            "blouse",
            "blue",
            "blur",
            "blush",
            "board",
            "boat",
            "body",
            "boil",
            "bomb",
            "bone",
            "bonus",
            "book",
            "boost",
            "border",
            "boring",
            "borrow",
            "boss",
            "bottom",
            "bounce",
            "box",
            "boy",
            "bracket",
            "brain",
            "brand",
            "brass",
            "brave",
            "bread",
            "breeze",
            "brick",
            "bridge",
            "brief",
            "bright",
            "bring",
            "brisk",
            "broccoli",
            "broken",
            "bronze",
            "broom",
            "brother",
            "brown",
            "brush",
            "bubble",
            "buddy",
            "budget",
            "buffalo",
            "build",
            "bulb",
            "bulk",
            "bullet",
            "bundle",
            "bunker",
            "burden",
            "burger",
            "burst",
            "bus",
            "business",
            "busy",
            "butter",
            "buyer",
            "buzz",
            "cabbage",
            "cabin",
            "cable",
            "cactus",
            "cage",
            "cake",
            "call",
            "calm",
            "camera",
            "camp",
            "can",
            "canal",
            "cancel",
            "candy",
            "cannon",
            "canoe",
            "canvas",
            "canyon",
            "capable",
            "capital",
            "captain",
            "car",
            "carbon",
            "card",
            "cargo",
            "carpet",
            "carry",
            "cart",
            "case",
            "cash",
            "casino",
            "castle",
            "casual",
            "cat",
            "catalog",
            "catch",
            "category",
            "cattle",
            "caught",
            "cause",
            "caution",
            "cave",
            "ceiling",
            "celery",
            "cement",
            "census",
            "century",
            "cereal",
            "certain",
            "chair",
            "chalk",
            "champion",
            "change",
            "chaos",
            "chapter",
            "charge",
            "chase",
            "chat",
            "cheap",
            "check",
            "cheese",
            "chef",
            "cherry",
            "chest",
            "chicken",
            "chief",
            "child",
            "chimney",
            "choice",
            "choose",
            "chronic",
            "chuckle",
            "chunk",
            "churn",
            "cigar",
            "cinnamon",
            "circle",
            "citizen",
            "city",
            "civil",
            "claim",
            "clap",
            "clarify",
            "claw",
            "clay",
            "clean",
            "clerk",
            "clever",
            "click",
            "client",
            "cliff",
            "climb",
            "clinic",
            "clip",
            "clock",
            "clog",
            "close",
            "cloth",
            "cloud",
            "clown",
            "club",
            "clump",
            "cluster",
            "clutch",
            "coach",
            "coast",
            "coconut",
            "code",
            "coffee",
            "coil",
            "coin",
            "collect",
            "color",
            "column",
            "combine",
            "come",
            "comfort",
            "comic",
            "common",
            "company",
            "concert",
            "conduct",
            "confirm",
            "congress",
            "connect",
            "consider",
            "control",
            "convince",
            "cook",
            "cool",
            "copper",
            "copy",
            "coral",
            "core",
            "corn",
            "correct",
            "cost",
            "cotton",
            "couch",
            "country",
            "couple",
            "course",
            "cousin",
            "cover",
            "coyote",
            "crack",
            "cradle",
            "craft",
            "cram",
            "crane",
            "crash",
            "crater",
            "crawl",
            "crazy",
            "cream",
            "credit",
            "creek",
            "crew",
            "cricket",
            "crime",
            "crisp",
            "critic",
            "crop",
            "cross",
            "crouch",
            "crowd",
            "crucial",
            "cruel",
            "cruise",
            "crumble",
            "crunch",
            "crush",
            "cry",
            "crystal",
            "cube",
            "culture",
            "cup",
            "cupboard",
            "curious",
            "current",
            "curtain",
            "curve",
            "cushion",
            "custom",
            "cute",
            "cycle",
            "dad",
            "damage",
            "damp",
            "dance",
            "danger",
            "daring",
            "dash",
            "daughter",
            "dawn",
            "day",
            "deal",
            "debate",
            "debris",
            "decade",
            "december",
            "decide",
            "decline",
            "decorate",
            "decrease",
            "deer",
            "defense",
            "define",
            "defy",
            "degree",
            "delay",
            "deliver",
            "demand",
            "demise",
            "denial",
            "dentist",
            "deny",
            "depart",
            "depend",
            "deposit",
            "depth",
            "deputy",
            "derive",
            "describe",
            "desert",
            "design",
            "desk",
            "despair",
            "destroy",
            "detail",
            "detect",
            "develop",
            "device",
            "devote",
            "diagram",
            "dial",
            "diamond",
            "diary",
            "dice",
            "diesel",
            "diet",
            "differ",
            "digital",
            "dignity",
            "dilemma",
            "dinner",
            "dinosaur",
            "direct",
            "dirt",
            "disagree",
            "discover",
            "disease",
            "dish",
            "dismiss",
            "disorder",
            "display",
            "distance",
            "divert",
            "divide",
            "divorce",
            "dizzy",
            "doctor",
            "document",
            "dog",
            "doll",
            "dolphin",
            "domain",
            "donate",
            "donkey",
            "donor",
            "door",
            "dose",
            "double",
            "dove",
            "draft",
            "dragon",
            "drama",
            "drastic",
            "draw",
            "dream",
            "dress",
            "drift",
            "drill",
            "drink",
            "drip",
            "drive",
            "drop",
            "drum",
            "dry",
            "duck",
            "dumb",
            "dune",
            "during",
            "dust",
            "dutch",
            "duty",
            "dwarf",
            "dynamic",
            "eager",
            "eagle",
            "early",
            "earn",
            "earth",
            "easily",
            "east",
            "easy",
            "echo",
            "ecology",
            "economy",
            "edge",
            "edit",
            "educate",
            "effort",
            "egg",
            "eight",
            "either",
            "elbow",
            "elder",
            "electric",
            "elegant",
            "element",
            "elephant",
            "elevator",
            "elite",
            "else",
            "embark",
            "embody",
            "embrace",
            "emerge",
            "emotion",
            "employ",
            "empower",
            "empty",
            "enable",
            "enact",
            "end",
            "endless",
            "endorse",
            "enemy",
            "energy",
            "enforce",
            "engage",
            "engine",
            "enhance",
            "enjoy",
            "enlist",
            "enough",
            "enrich",
            "enroll",
            "ensure",
            "enter",
            "entire",
            "entry",
            "envelope",
            "episode",
            "equal",
            "equip",
            "era",
            "erase",
            "erode",
            "erosion",
            "error",
            "erupt",
            "escape",
            "essay",
            "essence",
            "estate",
            "eternal",
            "ethics",
            "evidence",
            "evil",
            "evoke",
            "evolve",
            "exact",
            "example",
            "excess",
            "exchange",
            "excite",
            "exclude",
            "excuse",
            "execute",
            "exercise",
            "exhaust",
            "exhibit",
            "exile",
            "exist",
            "exit",
            "exotic",
            "expand",
            "expect",
            "expire",
            "explain",
            "expose",
            "express",
            "extend",
            "extra",
            "eye",
            "eyebrow",
            "fabric",
            "face",
            "faculty",
            "fade",
            "faint",
            "faith",
            "fall",
            "false",
            "fame",
            "family",
            "famous",
            "fan",
            "fancy",
            "fantasy",
            "farm",
            "fashion",
            "fat",
            "fatal",
            "father",
            "fatigue",
            "fault",
            "favorite",
            "feature",
            "february",
            "federal",
            "fee",
            "feed",
            "feel",
            "female",
            "fence",
            "festival",
            "fetch",
            "fever",
            "few",
            "fiber",
            "fiction",
            "field",
            "figure",
            "file",
            "film",
            "filter",
            "final",
            "find",
            "fine",
            "finger",
            "finish",
            "fire",
            "firm",
            "first",
            "fiscal",
            "fish",
            "fit",
            "fitness",
            "fix",
            "flag",
            "flame",
            "flash",
            "flat",
            "flavor",
            "flee",
            "flight",
            "flip",
            "float",
            "flock",
            "floor",
            "flower",
            "fluid",
            "flush",
            "fly",
            "foam",
            "focus",
            "fog",
            "foil",
            "fold",
            "follow",
            "food",
            "foot",
            "force",
            "forest",
            "forget",
            "fork",
            "fortune",
            "forum",
            "forward",
            "fossil",
            "foster",
            "found",
            "fox",
            "fragile",
            "frame",
            "frequent",
            "fresh",
            "friend",
            "fringe",
            "frog",
            "front",
            "frost",
            "frown",
            "frozen",
            "fruit",
            "fuel",
            "fun",
            "funny",
            "furnace",
            "fury",
            "future",
            "gadget",
            "gain",
            "galaxy",
            "gallery",
            "game",
            "gap",
            "garage",
            "garbage",
            "garden",
            "garlic",
            "garment",
            "gas",
            "gasp",
            "gate",
            "gather",
            "gauge",
            "gaze",
            "general",
            "genius",
            "genre",
            "gentle",
            "genuine",
            "gesture",
            "ghost",
            "giant",
            "gift",
            "giggle",
            "ginger",
            "giraffe",
            "girl",
            "give",
            "glad",
            "glance",
            "glare",
            "glass",
            "glide",
            "glimpse",
            "globe",
            "gloom",
            "glory",
            "glove",
            "glow",
            "glue",
            "goat",
            "goddess",
            "gold",
            "good",
            "goose",
            "gorilla",
            "gospel",
            "gossip",
            "govern",
            "gown",
            "grab",
            "grace",
            "grain",
            "grant",
            "grape",
            "grass",
            "gravity",
            "great",
            "green",
            "grid",
            "grief",
            "grit",
            "grocery",
            "group",
            "grow",
            "grunt",
            "guard",
            "guess",
            "guide",
            "guilt",
            "guitar",
            "gun",
            "gym",
            "habit",
            "hair",
            "half",
            "hammer",
            "hamster",
            "hand",
            "happy",
            "harbor",
            "hard",
            "harsh",
            "harvest",
            "hat",
            "have",
            "hawk",
            "hazard",
            "head",
            "health",
            "heart",
            "heavy",
            "hedgehog",
            "height",
            "hello",
            "helmet",
            "help",
            "hen",
            "hero",
            "hidden",
            "high",
            "hill",
            "hint",
            "hip",
            "hire",
            "history",
            "hobby",
            "hockey",
            "hold",
            "hole",
            "holiday",
            "hollow",
            "home",
            "honey",
            "hood",
            "hope",
            "horn",
            "horror",
            "horse",
            "hospital",
            "host",
            "hotel",
            "hour",
            "hover",
            "hub",
            "huge",
            "human",
            "humble",
            "humor",
            "hundred",
            "hungry",
            "hunt",
            "hurdle",
            "hurry",
            "hurt",
            "husband",
            "hybrid",
            "ice",
            "icon",
            "idea",
            "identify",
            "idle",
            "ignore",
            "ill",
            "illegal",
            "illness",
            "image",
            "imitate",
            "immense",
            "immune",
            "impact",
            "impose",
            "improve",
            "impulse",
            "inch",
            "include",
            "income",
            "increase",
            "index",
            "indicate",
            "indoor",
            "industry",
            "infant",
            "inflict",
            "inform",
            "inhale",
            "inherit",
            "initial",
            "inject",
            "injury",
            "inmate",
            "inner",
            "innocent",
            "input",
            "inquiry",
            "insane",
            "insect",
            "inside",
            "inspire",
            "install",
            "intact",
            "interest",
            "into",
            "invest",
            "invite",
            "involve",
            "iron",
            "island",
            "isolate",
            "issue",
            "item",
            "ivory",
            "jacket",
            "jaguar",
            "jar",
            "jazz",
            "jealous",
            "jeans",
            "jelly",
            "jewel",
            "job",
            "join",
            "joke",
            "journey",
            "joy",
            "judge",
            "juice",
            "jump",
            "jungle",
            "junior",
            "junk",
            "just",
            "kangaroo",
            "keen",
            "keep",
            "ketchup",
            "key",
            "kick",
            "kid",
            "kidney",
            "kind",
            "kingdom",
            "kiss",
            "kit",
            "kitchen",
            "kite",
            "kitten",
            "kiwi",
            "knee",
            "knife",
            "knock",
            "know",
            "lab",
            "label",
            "labor",
            "ladder",
            "lady",
            "lake",
            "lamp",
            "language",
            "laptop",
            "large",
            "later",
            "latin",
            "laugh",
            "laundry",
            "lava",
            "law",
            "lawn",
            "lawsuit",
            "layer",
            "lazy",
            "leader",
            "leaf",
            "learn",
            "leave",
            "lecture",
            "left",
            "leg",
            "legal",
            "legend",
            "leisure",
            "lemon",
            "lend",
            "length",
            "lens",
            "leopard",
            "lesson",
            "letter",
            "level",
            "liar",
            "liberty",
            "library",
            "license",
            "life",
            "lift",
            "light",
            "like",
            "limb",
            "limit",
            "link",
            "lion",
            "liquid",
            "list",
            "little",
            "live",
            "lizard",
            "load",
            "loan",
            "lobster",
            "local",
            "lock",
            "logic",
            "lonely",
            "long",
            "loop",
            "lottery",
            "loud",
            "lounge",
            "love",
            "loyal",
            "lucky",
            "luggage",
            "lumber",
            "lunar",
            "lunch",
            "luxury",
            "lyrics",
            "machine",
            "mad",
            "magic",
            "magnet",
            "maid",
            "mail",
            "main",
            "major",
            "make",
            "mammal",
            "man",
            "manage",
            "mandate",
            "mango",
            "mansion",
            "manual",
            "maple",
            "marble",
            "march",
            "margin",
            "marine",
            "market",
            "marriage",
            "mask",
            "mass",
            "master",
            "match",
            "material",
            "math",
            "matrix",
            "matter",
            "maximum",
            "maze",
            "meadow",
            "mean",
            "measure",
            "meat",
            "mechanic",
            "medal",
            "media",
            "melody",
            "melt",
            "member",
            "memory",
            "mention",
            "menu",
            "mercy",
            "merge",
            "merit",
            "merry",
            "mesh",
            "message",
            "metal",
            "method",
            "middle",
            "midnight",
            "milk",
            "million",
            "mimic",
            "mind",
            "minimum",
            "minor",
            "minute",
            "miracle",
            "mirror",
            "misery",
            "miss",
            "mistake",
            "mix",
            "mixed",
            "mixture",
            "mobile",
            "model",
            "modify",
            "mom",
            "moment",
            "monitor",
            "monkey",
            "monster",
            "month",
            "moon",
            "moral",
            "more",
            "morning",
            "mosquito",
            "mother",
            "motion",
            "motor",
            "mountain",
            "mouse",
            "move",
            "movie",
            "much",
            "muffin",
            "mule",
            "multiply",
            "muscle",
            "museum",
            "mushroom",
            "music",
            "must",
            "mutual",
            "myself",
            "mystery",
            "myth",
            "naive",
            "name",
            "napkin",
            "narrow",
            "nasty",
            "nation",
            "nature",
            "near",
            "neck",
            "need",
            "negative",
            "neglect",
            "neither",
            "nephew",
            "nerve",
            "nest",
            "net",
            "network",
            "neutral",
            "never",
            "news",
            "next",
            "nice",
            "night",
            "noble",
            "noise",
            "nominee",
            "noodle",
            "normal",
            "north",
            "nose",
            "notable",
            "note",
            "nothing",
            "notice",
            "novel",
            "now",
            "nuclear",
            "number",
            "nurse",
            "nut",
            "oak",
            "obey",
            "object",
            "oblige",
            "obscure",
            "observe",
            "obtain",
            "obvious",
            "occur",
            "ocean",
            "october",
            "odor",
            "off",
            "offer",
            "office",
            "often",
            "oil",
            "okay",
            "old",
            "olive",
            "olympic",
            "omit",
            "once",
            "one",
            "onion",
            "online",
            "only",
            "open",
            "opera",
            "opinion",
            "oppose",
            "option",
            "orange",
            "orbit",
            "orchard",
            "order",
            "ordinary",
            "organ",
            "orient",
            "original",
            "orphan",
            "ostrich",
            "other",
            "outdoor",
            "outer",
            "output",
            "outside",
            "oval",
            "oven",
            "over",
            "own",
            "owner",
            "oxygen",
            "oyster",
            "ozone",
            "pact",
            "paddle",
            "page",
            "pair",
            "palace",
            "palm",
            "panda",
            "panel",
            "panic",
            "panther",
            "paper",
            "parade",
            "parent",
            "park",
            "parrot",
            "party",
            "pass",
            "patch",
            "path",
            "patient",
            "patrol",
            "pattern",
            "pause",
            "pave",
            "payment",
            "peace",
            "peanut",
            "pear",
            "peasant",
            "pelican",
            "pen",
            "penalty",
            "pencil",
            "people",
            "pepper",
            "perfect",
            "permit",
            "person",
            "pet",
            "phone",
            "photo",
            "phrase",
            "physical",
            "piano",
            "picnic",
            "picture",
            "piece",
            "pig",
            "pigeon",
            "pill",
            "pilot",
            "pink",
            "pioneer",
            "pipe",
            "pistol",
            "pitch",
            "pizza",
            "place",
            "planet",
            "plastic",
            "plate",
            "play",
            "please",
            "pledge",
            "pluck",
            "plug",
            "plunge",
            "poem",
            "poet",
            "point",
            "polar",
            "pole",
            "police",
            "pond",
            "pony",
            "pool",
            "popular",
            "portion",
            "position",
            "possible",
            "post",
            "potato",
            "pottery",
            "poverty",
            "powder",
            "power",
            "practice",
            "praise",
            "predict",
            "prefer",
            "prepare",
            "present",
            "pretty",
            "prevent",
            "price",
            "pride",
            "primary",
            "print",
            "priority",
            "prison",
            "private",
            "prize",
            "problem",
            "process",
            "produce",
            "profit",
            "program",
            "project",
            "promote",
            "proof",
            "property",
            "prosper",
            "protect",
            "proud",
            "provide",
            "public",
            "pudding",
            "pull",
            "pulp",
            "pulse",
            "pumpkin",
            "punch",
            "pupil",
            "puppy",
            "purchase",
            "purity",
            "purpose",
            "purse",
            "push",
            "put",
            "puzzle",
            "pyramid",
            "quality",
            "quantum",
            "quarter",
            "question",
            "quick",
            "quit",
            "quiz",
            "quote",
            "rabbit",
            "raccoon",
            "race",
            "rack",
            "radar",
            "radio",
            "rail",
            "rain",
            "raise",
            "rally",
            "ramp",
            "ranch",
            "random",
            "range",
            "rapid",
            "rare",
            "rate",
            "rather",
            "raven",
            "raw",
            "razor",
            "ready",
            "real",
            "reason",
            "rebel",
            "rebuild",
            "recall",
            "receive",
            "recipe",
            "record",
            "recycle",
            "reduce",
            "reflect",
            "reform",
            "refuse",
            "region",
            "regret",
            "regular",
            "reject",
            "relax",
            "release",
            "relief",
            "rely",
            "remain",
            "remember",
            "remind",
            "remove",
            "render",
            "renew",
            "rent",
            "reopen",
            "repair",
            "repeat",
            "replace",
            "report",
            "require",
            "rescue",
            "resemble",
            "resist",
            "resource",
            "response",
            "result",
            "retire",
            "retreat",
            "return",
            "reunion",
            "reveal",
            "review",
            "reward",
            "rhythm",
            "rib",
            "ribbon",
            "rice",
            "rich",
            "ride",
            "ridge",
            "rifle",
            "right",
            "rigid",
            "ring",
            "riot",
            "ripple",
            "risk",
            "ritual",
            "rival",
            "river",
            "road",
            "roast",
            "robot",
            "robust",
            "rocket",
            "romance",
            "roof",
            "rookie",
            "room",
            "rose",
            "rotate",
            "rough",
            "round",
            "route",
            "royal",
            "rubber",
            "rude",
            "rug",
            "rule",
            "run",
            "runway",
            "rural",
            "sad",
            "saddle",
            "sadness",
            "safe",
            "sail",
            "salad",
            "salmon",
            "salon",
            "salt",
            "salute",
            "same",
            "sample",
            "sand",
            "satisfy",
            "satoshi",
            "sauce",
            "sausage",
            "save",
            "say",
            "scale",
            "scan",
            "scare",
            "scatter",
            "scene",
            "scheme",
            "school",
            "science",
            "scissors",
            "scorpion",
            "scout",
            "scrap",
            "screen",
            "script",
            "scrub",
            "sea",
            "search",
            "season",
            "seat",
            "second",
            "secret",
            "section",
            "security",
            "seed",
            "seek",
            "segment",
            "select",
            "sell",
            "seminar",
            "senior",
            "sense",
            "sentence",
            "series",
            "service",
            "session",
            "settle",
            "setup",
            "seven",
            "shadow",
            "shaft",
            "shallow",
            "share",
            "shed",
            "shell",
            "sheriff",
            "shield",
            "shift",
            "shine",
            "ship",
            "shiver",
            "shock",
            "shoe",
            "shoot",
            "shop",
            "short",
            "shoulder",
            "shove",
            "shrimp",
            "shrug",
            "shuffle",
            "shy",
            "sibling",
            "sick",
            "side",
            "siege",
            "sight",
            "sign",
            "silent",
            "silk",
            "silly",
            "silver",
            "similar",
            "simple",
            "since",
            "sing",
            "siren",
            "sister",
            "situate",
            "six",
            "size",
            "skate",
            "sketch",
            "ski",
            "skill",
            "skin",
            "skirt",
            "skull",
            "slab",
            "slam",
            "sleep",
            "slender",
            "slice",
            "slide",
            "slight",
            "slim",
            "slogan",
            "slot",
            "slow",
            "slush",
            "small",
            "smart",
            "smile",
            "smoke",
            "smooth",
            "snack",
            "snake",
            "snap",
            "sniff",
            "snow",
            "soap",
            "soccer",
            "social",
            "sock",
            "soda",
            "soft",
            "solar",
            "soldier",
            "solid",
            "solution",
            "solve",
            "someone",
            "song",
            "soon",
            "sorry",
            "sort",
            "soul",
            "sound",
            "soup",
            "source",
            "south",
            "space",
            "spare",
            "spatial",
            "spawn",
            "speak",
            "special",
            "speed",
            "spell",
            "spend",
            "sphere",
            "spice",
            "spider",
            "spike",
            "spin",
            "spirit",
            "split",
            "spoil",
            "sponsor",
            "spoon",
            "sport",
            "spot",
            "spray",
            "spread",
            "spring",
            "spy",
            "square",
            "squeeze",
            "squirrel",
            "stable",
            "stadium",
            "staff",
            "stage",
            "stairs",
            "stamp",
            "stand",
            "start",
            "state",
            "stay",
            "steak",
            "steel",
            "stem",
            "step",
            "stereo",
            "stick",
            "still",
            "sting",
            "stock",
            "stomach",
            "stone",
            "stool",
            "story",
            "stove",
            "strategy",
            "street",
            "strike",
            "strong",
            "struggle",
            "student",
            "stuff",
            "stumble",
            "style",
            "subject",
            "submit",
            "subway",
            "success",
            "such",
            "sudden",
            "suffer",
            "sugar",
            "suggest",
            "suit",
            "summer",
            "sun",
            "sunny",
            "sunset",
            "super",
            "supply",
            "supreme",
            "sure",
            "surface",
            "surge",
            "surprise",
            "surround",
            "survey",
            "suspect",
            "sustain",
            "swallow",
            "swamp",
            "swap",
            "swarm",
            "swear",
            "sweet",
            "swift",
            "swim",
            "swing",
            "switch",
            "sword",
            "symbol",
            "symptom",
            "syrup",
            "system",
            "table",
            "tackle",
            "tag",
            "tail",
            "talent",
            "talk",
            "tank",
            "tape",
            "target",
            "task",
            "taste",
            "tattoo",
            "taxi",
            "teach",
            "team",
            "tell",
            "ten",
            "tenant",
            "tennis",
            "tent",
            "term",
            "test",
            "text",
            "thank",
            "that",
            "theme",
            "then",
            "theory",
            "there",
            "they",
            "thing",
            "this",
            "thought",
            "three",
            "thrive",
            "throw",
            "thumb",
            "thunder",
            "ticket",
            "tide",
            "tiger",
            "tilt",
            "timber",
            "time",
            "tiny",
            "tip",
            "tired",
            "tissue",
            "title",
            "toast",
            "tobacco",
            "today",
            "toddler",
            "toe",
            "together",
            "toilet",
            "token",
            "tomato",
            "tomorrow",
            "tone",
            "tongue",
            "tonight",
            "tool",
            "tooth",
            "top",
            "topic",
            "topple",
            "torch",
            "tornado",
            "tortoise",
            "toss",
            "total",
            "tourist",
            "toward",
            "tower",
            "town",
            "toy",
            "track",
            "trade",
            "traffic",
            "tragic",
            "train",
            "transfer",
            "trap",
            "trash",
            "travel",
            "tray",
            "treat",
            "tree",
            "trend",
            "trial",
            "tribe",
            "trick",
            "trigger",
            "trim",
            "trip",
            "trophy",
            "trouble",
            "truck",
            "true",
            "truly",
            "trumpet",
            "trust",
            "truth",
            "try",
            "tube",
            "tuition",
            "tumble",
            "tuna",
            "tunnel",
            "turkey",
            "turn",
            "turtle",
            "twelve",
            "twenty",
            "twice",
            "twin",
            "twist",
            "two",
            "type",
            "typical",
            "ugly",
            "umbrella",
            "unable",
            "unaware",
            "uncle",
            "uncover",
            "under",
            "undo",
            "unfair",
            "unfold",
            "unhappy",
            "uniform",
            "unique",
            "unit",
            "universe",
            "unknown",
            "unlock",
            "until",
            "unusual",
            "unveil",
            "update",
            "upgrade",
            "uphold",
            "upon",
            "upper",
            "upset",
            "urban",
            "urge",
            "usage",
            "use",
            "used",
            "useful",
            "useless",
            "usual",
            "utility",
            "vacant",
            "vacuum",
            "vague",
            "valid",
            "valley",
            "valve",
            "van",
            "vanish",
            "vapor",
            "various",
            "vast",
            "vault",
            "vehicle",
            "velvet",
            "vendor",
            "venture",
            "venue",
            "verb",
            "verify",
            "version",
            "very",
            "vessel",
            "veteran",
            "viable",
            "vibrant",
            "vicious",
            "victory",
            "video",
            "view",
            "village",
            "vintage",
            "violin",
            "virtual",
            "virus",
            "visa",
            "visit",
            "visual",
            "vital",
            "vivid",
            "vocal",
            "voice",
            "void",
            "volcano",
            "volume",
            "vote",
            "voyage",
            "wage",
            "wagon",
            "wait",
            "walk",
            "wall",
            "walnut",
            "want",
            "warfare",
            "warm",
            "warrior",
            "wash",
            "wasp",
            "waste",
            "water",
            "wave",
            "way",
            "wealth",
            "weapon",
            "wear",
            "weasel",
            "weather",
            "web",
            "wedding",
            "weekend",
            "weird",
            "welcome",
            "west",
            "wet",
            "whale",
            "what",
            "wheat",
            "wheel",
            "when",
            "where",
            "whip",
            "whisper",
            "wide",
            "width",
            "wife",
            "wild",
            "will",
            "win",
            "window",
            "wine",
            "wing",
            "wink",
            "winner",
            "winter",
            "wire",
            "wisdom",
            "wise",
            "wish",
            "witness",
            "wolf",
            "woman",
            "wonder",
            "wood",
            "wool",
            "word",
            "work",
            "world",
            "worry",
            "worth",
            "wrap",
            "wreck",
            "wrestle",
            "wrist",
            "write",
            "wrong",
            "yard",
            "year",
            "yellow",
            "you",
            "young",
            "youth",
            "zebra",
            "zero",
            "zone",
            "zoo");
}
