/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_ethereum_BREthereumWallet */

#ifndef _Included_com_breadwallet_core_ethereum_BREthereumWallet
#define _Included_com_breadwallet_core_ethereum_BREthereumWallet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_ethereum_BREthereumWallet
 * Method:    getBalance
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumWallet_getBalance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
