package com.breadwallet.crypto.jni.bitcoin;
import com.breadwallet.crypto.jni.CryptoLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bitcoin/BRWalletManager.h:84</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class BRWalletManagerEvent extends Structure {
	/**
	 * @see BRWalletManagerEventType<br>
	 * C type : BRWalletManagerEventType
	 */
	public int type;
	/** C type : u_union */
	public u_union u;
	/** <i>native declaration : bitcoin/BRWalletManager.h:83</i> */
	public static class u_union extends Union {
		/** C type : syncStopped_struct */
		public syncStopped_struct syncStopped;
		/** C type : blockHeightUpdated_struct */
		public blockHeightUpdated_struct blockHeightUpdated;
		/** <i>native declaration : bitcoin/BRWalletManager.h:79</i> */
		public static class syncStopped_struct extends Structure {
			public int error;
			public syncStopped_struct() {
				super();
			}
			protected List<String> getFieldOrder() {
				return Arrays.asList("error");
			}
			public syncStopped_struct(int error) {
				super();
				this.error = error;
			}
			public syncStopped_struct(Pointer peer) {
				super(peer);
			}
			public static class ByReference extends syncStopped_struct implements Structure.ByReference {
				
			};
			public static class ByValue extends syncStopped_struct implements Structure.ByValue {
				
			};
		};
		/** <i>native declaration : bitcoin/BRWalletManager.h:82</i> */
		public static class blockHeightUpdated_struct extends Structure {
			public int value;
			public blockHeightUpdated_struct() {
				super();
			}
			protected List<String> getFieldOrder() {
				return Arrays.asList("value");
			}
			public blockHeightUpdated_struct(int value) {
				super();
				this.value = value;
			}
			public blockHeightUpdated_struct(Pointer peer) {
				super(peer);
			}
			public static class ByReference extends blockHeightUpdated_struct implements Structure.ByReference {
				
			};
			public static class ByValue extends blockHeightUpdated_struct implements Structure.ByValue {
				
			};
		};
		public u_union() {
			super();
		}
		/** @param syncStopped C type : syncStopped_struct */
		public u_union(syncStopped_struct syncStopped) {
			super();
			this.syncStopped = syncStopped;
			setType(syncStopped_struct.class);
		}
		/** @param blockHeightUpdated C type : blockHeightUpdated_struct */
		public u_union(blockHeightUpdated_struct blockHeightUpdated) {
			super();
			this.blockHeightUpdated = blockHeightUpdated;
			setType(blockHeightUpdated_struct.class);
		}
		public u_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends u_union implements Structure.ByReference {
			
		};
		public static class ByValue extends u_union implements Structure.ByValue {
			
		};
	};
	public BRWalletManagerEvent() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "u");
	}
	/**
	 * @param type @see BRWalletManagerEventType<br>
	 * C type : BRWalletManagerEventType<br>
	 * @param u C type : u_union
	 */
	public BRWalletManagerEvent(int type, u_union u) {
		super();
		this.type = type;
		this.u = u;
	}
	public BRWalletManagerEvent(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends BRWalletManagerEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends BRWalletManagerEvent implements Structure.ByValue {
		
	};

	@Override
	public void read() {
		super.read();
		switch (type){
			case CryptoLibrary.BRWalletManagerEventType.BITCOIN_WALLET_MANAGER_BLOCK_HEIGHT_UPDATED:
				u.setType(u_union.blockHeightUpdated_struct.class);
				u.read();
				break;
			case CryptoLibrary.BRWalletManagerEventType.BITCOIN_WALLET_MANAGER_SYNC_STOPPED:
				u.setType(u_union.syncStopped_struct.class);
				u.read();
				break;
		}
	}
}
