/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCorePaymentProtocolInvoiceRequest */

#ifndef _Included_com_breadwallet_core_BRCorePaymentProtocolInvoiceRequest
#define _Included_com_breadwallet_core_BRCorePaymentProtocolInvoiceRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCorePaymentProtocolInvoiceRequest
 * Method:    createPaymentProtocolInvoiceRequest
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCorePaymentProtocolInvoiceRequest_createPaymentProtocolInvoiceRequest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
