/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCoreAddress */

#ifndef _Included_com_breadwallet_core_BRCoreAddress
#define _Included_com_breadwallet_core_BRCoreAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCoreAddress
 * Method:    stringify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_BRCoreAddress_stringify
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
