/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCoreMasterPubKey */

#ifndef _Included_com_breadwallet_core_BRCoreMasterPubKey
#define _Included_com_breadwallet_core_BRCoreMasterPubKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    createJniCoreMasterPubKey
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_createJniCoreMasterPubKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    bip32BitIDKey
 * Signature: ([BILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_bip32BitIDKey
  (JNIEnv *, jclass, jbyteArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
