/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCorePaymentProtocolRequest */

#ifndef _Included_com_breadwallet_core_BRCorePaymentProtocolRequest
#define _Included_com_breadwallet_core_BRCorePaymentProtocolRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCorePaymentProtocolRequest
 * Method:    createPaymentProtocolRequest
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCorePaymentProtocolRequest_createPaymentProtocolRequest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
