/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCorePaymentProtocolEncryptedMessage */

#ifndef _Included_com_breadwallet_core_BRCorePaymentProtocolEncryptedMessage
#define _Included_com_breadwallet_core_BRCorePaymentProtocolEncryptedMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCorePaymentProtocolEncryptedMessage
 * Method:    createPaymentProtocolEncryptedMessage
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCorePaymentProtocolEncryptedMessage_createPaymentProtocolEncryptedMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
