/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCorePaymentProtocolPayment */

#ifndef _Included_com_breadwallet_core_BRCorePaymentProtocolPayment
#define _Included_com_breadwallet_core_BRCorePaymentProtocolPayment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCorePaymentProtocolPayment
 * Method:    createPaymentProtocolPayment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCorePaymentProtocolPayment_createPaymentProtocolPayment
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
