/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_ethereum_BREthereumTransfer */

#ifndef _Included_com_breadwallet_core_ethereum_BREthereumTransfer
#define _Included_com_breadwallet_core_ethereum_BREthereumTransfer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
