/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ContractGetBytecode.proto */

#ifndef PROTOBUF_C_ContractGetBytecode_2eproto__INCLUDED
#define PROTOBUF_C_ContractGetBytecode_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"
#include "QueryHeader.pb-c.h"
#include "ResponseHeader.pb-c.h"

typedef struct _Proto__ContractGetBytecodeQuery Proto__ContractGetBytecodeQuery;
typedef struct _Proto__ContractGetBytecodeResponse Proto__ContractGetBytecodeResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Get the bytecode for a smart contract instance 
 */
struct  _Proto__ContractGetBytecodeQuery
{
  ProtobufCMessage base;
  /*
   * standard info sent from client to node, including the signed payment, and what kind of response is requested (cost, state proof, both, or neither).
   */
  Proto__QueryHeader *header;
  /*
   * the contract for which information is requested
   */
  Proto__ContractID *contractid;
};
#define PROTO__CONTRACT_GET_BYTECODE_QUERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__contract_get_bytecode_query__descriptor) \
    , NULL, NULL }


/*
 * Response when the client sends the node ContractGetBytecodeQuery 
 */
struct  _Proto__ContractGetBytecodeResponse
{
  ProtobufCMessage base;
  /*
   *standard response from node to client, including the requested fields: cost, or state proof, or both, or neither
   */
  Proto__ResponseHeader *header;
  /*
   * the bytecode
   */
  ProtobufCBinaryData bytecode;
};
#define PROTO__CONTRACT_GET_BYTECODE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__contract_get_bytecode_response__descriptor) \
    , NULL, {0,NULL} }


/* Proto__ContractGetBytecodeQuery methods */
void   proto__contract_get_bytecode_query__init
                     (Proto__ContractGetBytecodeQuery         *message);
size_t proto__contract_get_bytecode_query__get_packed_size
                     (const Proto__ContractGetBytecodeQuery   *message);
size_t proto__contract_get_bytecode_query__pack
                     (const Proto__ContractGetBytecodeQuery   *message,
                      uint8_t             *out);
size_t proto__contract_get_bytecode_query__pack_to_buffer
                     (const Proto__ContractGetBytecodeQuery   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContractGetBytecodeQuery *
       proto__contract_get_bytecode_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__contract_get_bytecode_query__free_unpacked
                     (Proto__ContractGetBytecodeQuery *message,
                      ProtobufCAllocator *allocator);
/* Proto__ContractGetBytecodeResponse methods */
void   proto__contract_get_bytecode_response__init
                     (Proto__ContractGetBytecodeResponse         *message);
size_t proto__contract_get_bytecode_response__get_packed_size
                     (const Proto__ContractGetBytecodeResponse   *message);
size_t proto__contract_get_bytecode_response__pack
                     (const Proto__ContractGetBytecodeResponse   *message,
                      uint8_t             *out);
size_t proto__contract_get_bytecode_response__pack_to_buffer
                     (const Proto__ContractGetBytecodeResponse   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContractGetBytecodeResponse *
       proto__contract_get_bytecode_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__contract_get_bytecode_response__free_unpacked
                     (Proto__ContractGetBytecodeResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__ContractGetBytecodeQuery_Closure)
                 (const Proto__ContractGetBytecodeQuery *message,
                  void *closure_data);
typedef void (*Proto__ContractGetBytecodeResponse_Closure)
                 (const Proto__ContractGetBytecodeResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__contract_get_bytecode_query__descriptor;
extern const ProtobufCMessageDescriptor proto__contract_get_bytecode_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ContractGetBytecode_2eproto__INCLUDED */
