/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ContractCall.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ContractCall.pb-c.h"
void   proto__contract_call_transaction_body__init
                     (Proto__ContractCallTransactionBody         *message)
{
  static const Proto__ContractCallTransactionBody init_value = PROTO__CONTRACT_CALL_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__contract_call_transaction_body__get_packed_size
                     (const Proto__ContractCallTransactionBody *message)
{
  assert(message->base.descriptor == &proto__contract_call_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__contract_call_transaction_body__pack
                     (const Proto__ContractCallTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__contract_call_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__contract_call_transaction_body__pack_to_buffer
                     (const Proto__ContractCallTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__contract_call_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ContractCallTransactionBody *
       proto__contract_call_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ContractCallTransactionBody *)
     protobuf_c_message_unpack (&proto__contract_call_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__contract_call_transaction_body__free_unpacked
                     (Proto__ContractCallTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__contract_call_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__contract_call_transaction_body__field_descriptors[4] =
{
  {
    "contractID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractCallTransactionBody, contractid),
    &proto__contract_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gas",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractCallTransactionBody, gas),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractCallTransactionBody, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "functionParameters",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractCallTransactionBody, functionparameters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__contract_call_transaction_body__field_indices_by_name[] = {
  2,   /* field[2] = amount */
  0,   /* field[0] = contractID */
  3,   /* field[3] = functionParameters */
  1,   /* field[1] = gas */
};
static const ProtobufCIntRange proto__contract_call_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__contract_call_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ContractCallTransactionBody",
  "ContractCallTransactionBody",
  "Proto__ContractCallTransactionBody",
  "proto",
  sizeof(Proto__ContractCallTransactionBody),
  4,
  proto__contract_call_transaction_body__field_descriptors,
  proto__contract_call_transaction_body__field_indices_by_name,
  1,  proto__contract_call_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__contract_call_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
