/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ContractGetRecords.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ContractGetRecords.pb-c.h"
void   proto__contract_get_records_query__init
                     (Proto__ContractGetRecordsQuery         *message)
{
  static const Proto__ContractGetRecordsQuery init_value = PROTO__CONTRACT_GET_RECORDS_QUERY__INIT;
  *message = init_value;
}
size_t proto__contract_get_records_query__get_packed_size
                     (const Proto__ContractGetRecordsQuery *message)
{
  assert(message->base.descriptor == &proto__contract_get_records_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__contract_get_records_query__pack
                     (const Proto__ContractGetRecordsQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__contract_get_records_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__contract_get_records_query__pack_to_buffer
                     (const Proto__ContractGetRecordsQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__contract_get_records_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ContractGetRecordsQuery *
       proto__contract_get_records_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ContractGetRecordsQuery *)
     protobuf_c_message_unpack (&proto__contract_get_records_query__descriptor,
                                allocator, len, data);
}
void   proto__contract_get_records_query__free_unpacked
                     (Proto__ContractGetRecordsQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__contract_get_records_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__contract_get_records_response__init
                     (Proto__ContractGetRecordsResponse         *message)
{
  static const Proto__ContractGetRecordsResponse init_value = PROTO__CONTRACT_GET_RECORDS_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__contract_get_records_response__get_packed_size
                     (const Proto__ContractGetRecordsResponse *message)
{
  assert(message->base.descriptor == &proto__contract_get_records_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__contract_get_records_response__pack
                     (const Proto__ContractGetRecordsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__contract_get_records_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__contract_get_records_response__pack_to_buffer
                     (const Proto__ContractGetRecordsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__contract_get_records_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ContractGetRecordsResponse *
       proto__contract_get_records_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ContractGetRecordsResponse *)
     protobuf_c_message_unpack (&proto__contract_get_records_response__descriptor,
                                allocator, len, data);
}
void   proto__contract_get_records_response__free_unpacked
                     (Proto__ContractGetRecordsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__contract_get_records_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__contract_get_records_query__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractGetRecordsQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contractID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractGetRecordsQuery, contractid),
    &proto__contract_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__contract_get_records_query__field_indices_by_name[] = {
  1,   /* field[1] = contractID */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__contract_get_records_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__contract_get_records_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ContractGetRecordsQuery",
  "ContractGetRecordsQuery",
  "Proto__ContractGetRecordsQuery",
  "proto",
  sizeof(Proto__ContractGetRecordsQuery),
  2,
  proto__contract_get_records_query__field_descriptors,
  proto__contract_get_records_query__field_indices_by_name,
  1,  proto__contract_get_records_query__number_ranges,
  (ProtobufCMessageInit) proto__contract_get_records_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__contract_get_records_response__field_descriptors[3] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractGetRecordsResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contractID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ContractGetRecordsResponse, contractid),
    &proto__contract_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "records",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ContractGetRecordsResponse, n_records),
    offsetof(Proto__ContractGetRecordsResponse, records),
    &proto__transaction_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__contract_get_records_response__field_indices_by_name[] = {
  1,   /* field[1] = contractID */
  0,   /* field[0] = header */
  2,   /* field[2] = records */
};
static const ProtobufCIntRange proto__contract_get_records_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__contract_get_records_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ContractGetRecordsResponse",
  "ContractGetRecordsResponse",
  "Proto__ContractGetRecordsResponse",
  "proto",
  sizeof(Proto__ContractGetRecordsResponse),
  3,
  proto__contract_get_records_response__field_descriptors,
  proto__contract_get_records_response__field_indices_by_name,
  1,  proto__contract_get_records_response__number_ranges,
  (ProtobufCMessageInit) proto__contract_get_records_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
