/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ContractGetRecords.proto */

#ifndef PROTOBUF_C_ContractGetRecords_2eproto__INCLUDED
#define PROTOBUF_C_ContractGetRecords_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"
#include "TransactionRecord.pb-c.h"
#include "QueryHeader.pb-c.h"
#include "ResponseHeader.pb-c.h"

typedef struct _Proto__ContractGetRecordsQuery Proto__ContractGetRecordsQuery;
typedef struct _Proto__ContractGetRecordsResponse Proto__ContractGetRecordsResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Get all the records for a smart contract instance, for any function call (or the constructor call) during the last 25 hours, for which a Record was requested. 
 */
struct  _Proto__ContractGetRecordsQuery
{
  ProtobufCMessage base;
  /*
   * Standard info sent from client to node, including the signed payment, and what kind of response is requested (cost, state proof, both, or neither).
   */
  Proto__QueryHeader *header;
  /*
   * The smart contract instance for which the records should be retrieved
   */
  Proto__ContractID *contractid;
};
#define PROTO__CONTRACT_GET_RECORDS_QUERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__contract_get_records_query__descriptor) \
    , NULL, NULL }


/*
 * Response when the client sends the node ContractGetRecordsQuery 
 */
struct  _Proto__ContractGetRecordsResponse
{
  ProtobufCMessage base;
  /*
   *Standard response from node to client, including the requested fields: cost, or state proof, or both, or neither
   */
  Proto__ResponseHeader *header;
  /*
   * The smart contract instance that this record is for
   */
  Proto__ContractID *contractid;
  /*
   * List of records, each with contractCreateResult or contractCallResult as its body
   */
  size_t n_records;
  Proto__TransactionRecord **records;
};
#define PROTO__CONTRACT_GET_RECORDS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__contract_get_records_response__descriptor) \
    , NULL, NULL, 0,NULL }


/* Proto__ContractGetRecordsQuery methods */
void   proto__contract_get_records_query__init
                     (Proto__ContractGetRecordsQuery         *message);
size_t proto__contract_get_records_query__get_packed_size
                     (const Proto__ContractGetRecordsQuery   *message);
size_t proto__contract_get_records_query__pack
                     (const Proto__ContractGetRecordsQuery   *message,
                      uint8_t             *out);
size_t proto__contract_get_records_query__pack_to_buffer
                     (const Proto__ContractGetRecordsQuery   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContractGetRecordsQuery *
       proto__contract_get_records_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__contract_get_records_query__free_unpacked
                     (Proto__ContractGetRecordsQuery *message,
                      ProtobufCAllocator *allocator);
/* Proto__ContractGetRecordsResponse methods */
void   proto__contract_get_records_response__init
                     (Proto__ContractGetRecordsResponse         *message);
size_t proto__contract_get_records_response__get_packed_size
                     (const Proto__ContractGetRecordsResponse   *message);
size_t proto__contract_get_records_response__pack
                     (const Proto__ContractGetRecordsResponse   *message,
                      uint8_t             *out);
size_t proto__contract_get_records_response__pack_to_buffer
                     (const Proto__ContractGetRecordsResponse   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContractGetRecordsResponse *
       proto__contract_get_records_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__contract_get_records_response__free_unpacked
                     (Proto__ContractGetRecordsResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__ContractGetRecordsQuery_Closure)
                 (const Proto__ContractGetRecordsQuery *message,
                  void *closure_data);
typedef void (*Proto__ContractGetRecordsResponse_Closure)
                 (const Proto__ContractGetRecordsResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__contract_get_records_query__descriptor;
extern const ProtobufCMessageDescriptor proto__contract_get_records_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ContractGetRecords_2eproto__INCLUDED */
