/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CryptoGetAccountBalance.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CryptoGetAccountBalance.pb-c.h"
void   proto__crypto_get_account_balance_query__init
                     (Proto__CryptoGetAccountBalanceQuery         *message)
{
  static const Proto__CryptoGetAccountBalanceQuery init_value = PROTO__CRYPTO_GET_ACCOUNT_BALANCE_QUERY__INIT;
  *message = init_value;
}
size_t proto__crypto_get_account_balance_query__get_packed_size
                     (const Proto__CryptoGetAccountBalanceQuery *message)
{
  assert(message->base.descriptor == &proto__crypto_get_account_balance_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto_get_account_balance_query__pack
                     (const Proto__CryptoGetAccountBalanceQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto_get_account_balance_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto_get_account_balance_query__pack_to_buffer
                     (const Proto__CryptoGetAccountBalanceQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto_get_account_balance_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__CryptoGetAccountBalanceQuery *
       proto__crypto_get_account_balance_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__CryptoGetAccountBalanceQuery *)
     protobuf_c_message_unpack (&proto__crypto_get_account_balance_query__descriptor,
                                allocator, len, data);
}
void   proto__crypto_get_account_balance_query__free_unpacked
                     (Proto__CryptoGetAccountBalanceQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto_get_account_balance_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__crypto_get_account_balance_response__init
                     (Proto__CryptoGetAccountBalanceResponse         *message)
{
  static const Proto__CryptoGetAccountBalanceResponse init_value = PROTO__CRYPTO_GET_ACCOUNT_BALANCE_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__crypto_get_account_balance_response__get_packed_size
                     (const Proto__CryptoGetAccountBalanceResponse *message)
{
  assert(message->base.descriptor == &proto__crypto_get_account_balance_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto_get_account_balance_response__pack
                     (const Proto__CryptoGetAccountBalanceResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto_get_account_balance_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto_get_account_balance_response__pack_to_buffer
                     (const Proto__CryptoGetAccountBalanceResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto_get_account_balance_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__CryptoGetAccountBalanceResponse *
       proto__crypto_get_account_balance_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__CryptoGetAccountBalanceResponse *)
     protobuf_c_message_unpack (&proto__crypto_get_account_balance_response__descriptor,
                                allocator, len, data);
}
void   proto__crypto_get_account_balance_response__free_unpacked
                     (Proto__CryptoGetAccountBalanceResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto_get_account_balance_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__crypto_get_account_balance_query__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoGetAccountBalanceQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accountID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoGetAccountBalanceQuery, accountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto_get_account_balance_query__field_indices_by_name[] = {
  1,   /* field[1] = accountID */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__crypto_get_account_balance_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__crypto_get_account_balance_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.CryptoGetAccountBalanceQuery",
  "CryptoGetAccountBalanceQuery",
  "Proto__CryptoGetAccountBalanceQuery",
  "proto",
  sizeof(Proto__CryptoGetAccountBalanceQuery),
  2,
  proto__crypto_get_account_balance_query__field_descriptors,
  proto__crypto_get_account_balance_query__field_indices_by_name,
  1,  proto__crypto_get_account_balance_query__number_ranges,
  (ProtobufCMessageInit) proto__crypto_get_account_balance_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__crypto_get_account_balance_response__field_descriptors[3] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoGetAccountBalanceResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accountID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoGetAccountBalanceResponse, accountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balance",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoGetAccountBalanceResponse, balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto_get_account_balance_response__field_indices_by_name[] = {
  1,   /* field[1] = accountID */
  2,   /* field[2] = balance */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__crypto_get_account_balance_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__crypto_get_account_balance_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.CryptoGetAccountBalanceResponse",
  "CryptoGetAccountBalanceResponse",
  "Proto__CryptoGetAccountBalanceResponse",
  "proto",
  sizeof(Proto__CryptoGetAccountBalanceResponse),
  3,
  proto__crypto_get_account_balance_response__field_descriptors,
  proto__crypto_get_account_balance_response__field_indices_by_name,
  1,  proto__crypto_get_account_balance_response__number_ranges,
  (ProtobufCMessageInit) proto__crypto_get_account_balance_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
