/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CryptoUpdate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CryptoUpdate.pb-c.h"
void   proto__crypto_update_transaction_body__init
                     (Proto__CryptoUpdateTransactionBody         *message)
{
  static const Proto__CryptoUpdateTransactionBody init_value = PROTO__CRYPTO_UPDATE_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__crypto_update_transaction_body__get_packed_size
                     (const Proto__CryptoUpdateTransactionBody *message)
{
  assert(message->base.descriptor == &proto__crypto_update_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto_update_transaction_body__pack
                     (const Proto__CryptoUpdateTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto_update_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto_update_transaction_body__pack_to_buffer
                     (const Proto__CryptoUpdateTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto_update_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__CryptoUpdateTransactionBody *
       proto__crypto_update_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__CryptoUpdateTransactionBody *)
     protobuf_c_message_unpack (&proto__crypto_update_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__crypto_update_transaction_body__free_unpacked
                     (Proto__CryptoUpdateTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto_update_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__crypto_update_transaction_body__field_descriptors[12] =
{
  {
    "accountIDToUpdate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoUpdateTransactionBody, accountidtoupdate),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoUpdateTransactionBody, key),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proxyAccountID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoUpdateTransactionBody, proxyaccountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proxyFraction",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoUpdateTransactionBody, proxyfraction),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sendRecordThreshold",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Proto__CryptoUpdateTransactionBody, send_record_threshold_field_case),
    offsetof(Proto__CryptoUpdateTransactionBody, sendrecordthreshold),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiveRecordThreshold",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Proto__CryptoUpdateTransactionBody, receive_record_threshold_field_case),
    offsetof(Proto__CryptoUpdateTransactionBody, receiverecordthreshold),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewPeriod",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoUpdateTransactionBody, autorenewperiod),
    &proto__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expirationTime",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoUpdateTransactionBody, expirationtime),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiverSigRequired",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Proto__CryptoUpdateTransactionBody, receiver_sig_required_field_case),
    offsetof(Proto__CryptoUpdateTransactionBody, receiversigrequired),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sendRecordThresholdWrapper",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__CryptoUpdateTransactionBody, send_record_threshold_field_case),
    offsetof(Proto__CryptoUpdateTransactionBody, sendrecordthresholdwrapper),
    &google__protobuf__uint64_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiveRecordThresholdWrapper",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__CryptoUpdateTransactionBody, receive_record_threshold_field_case),
    offsetof(Proto__CryptoUpdateTransactionBody, receiverecordthresholdwrapper),
    &google__protobuf__uint64_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiverSigRequiredWrapper",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__CryptoUpdateTransactionBody, receiver_sig_required_field_case),
    offsetof(Proto__CryptoUpdateTransactionBody, receiversigrequiredwrapper),
    &google__protobuf__bool_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto_update_transaction_body__field_indices_by_name[] = {
  0,   /* field[0] = accountIDToUpdate */
  6,   /* field[6] = autoRenewPeriod */
  7,   /* field[7] = expirationTime */
  1,   /* field[1] = key */
  2,   /* field[2] = proxyAccountID */
  3,   /* field[3] = proxyFraction */
  5,   /* field[5] = receiveRecordThreshold */
  10,   /* field[10] = receiveRecordThresholdWrapper */
  8,   /* field[8] = receiverSigRequired */
  11,   /* field[11] = receiverSigRequiredWrapper */
  4,   /* field[4] = sendRecordThreshold */
  9,   /* field[9] = sendRecordThresholdWrapper */
};
static const ProtobufCIntRange proto__crypto_update_transaction_body__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor proto__crypto_update_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.CryptoUpdateTransactionBody",
  "CryptoUpdateTransactionBody",
  "Proto__CryptoUpdateTransactionBody",
  "proto",
  sizeof(Proto__CryptoUpdateTransactionBody),
  12,
  proto__crypto_update_transaction_body__field_descriptors,
  proto__crypto_update_transaction_body__field_indices_by_name,
  1,  proto__crypto_update_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__crypto_update_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
