/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CryptoTransfer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CryptoTransfer.pb-c.h"
void   proto__account_amount__init
                     (Proto__AccountAmount         *message)
{
  static const Proto__AccountAmount init_value = PROTO__ACCOUNT_AMOUNT__INIT;
  *message = init_value;
}
size_t proto__account_amount__get_packed_size
                     (const Proto__AccountAmount *message)
{
  assert(message->base.descriptor == &proto__account_amount__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__account_amount__pack
                     (const Proto__AccountAmount *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__account_amount__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__account_amount__pack_to_buffer
                     (const Proto__AccountAmount *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__account_amount__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__AccountAmount *
       proto__account_amount__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__AccountAmount *)
     protobuf_c_message_unpack (&proto__account_amount__descriptor,
                                allocator, len, data);
}
void   proto__account_amount__free_unpacked
                     (Proto__AccountAmount *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__account_amount__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__transfer_list__init
                     (Proto__TransferList         *message)
{
  static const Proto__TransferList init_value = PROTO__TRANSFER_LIST__INIT;
  *message = init_value;
}
size_t proto__transfer_list__get_packed_size
                     (const Proto__TransferList *message)
{
  assert(message->base.descriptor == &proto__transfer_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__transfer_list__pack
                     (const Proto__TransferList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__transfer_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__transfer_list__pack_to_buffer
                     (const Proto__TransferList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__transfer_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TransferList *
       proto__transfer_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TransferList *)
     protobuf_c_message_unpack (&proto__transfer_list__descriptor,
                                allocator, len, data);
}
void   proto__transfer_list__free_unpacked
                     (Proto__TransferList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__transfer_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__crypto_transfer_transaction_body__init
                     (Proto__CryptoTransferTransactionBody         *message)
{
  static const Proto__CryptoTransferTransactionBody init_value = PROTO__CRYPTO_TRANSFER_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__crypto_transfer_transaction_body__get_packed_size
                     (const Proto__CryptoTransferTransactionBody *message)
{
  assert(message->base.descriptor == &proto__crypto_transfer_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto_transfer_transaction_body__pack
                     (const Proto__CryptoTransferTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto_transfer_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto_transfer_transaction_body__pack_to_buffer
                     (const Proto__CryptoTransferTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto_transfer_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__CryptoTransferTransactionBody *
       proto__crypto_transfer_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__CryptoTransferTransactionBody *)
     protobuf_c_message_unpack (&proto__crypto_transfer_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__crypto_transfer_transaction_body__free_unpacked
                     (Proto__CryptoTransferTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto_transfer_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__account_amount__field_descriptors[2] =
{
  {
    "accountID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__AccountAmount, accountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__AccountAmount, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__account_amount__field_indices_by_name[] = {
  0,   /* field[0] = accountID */
  1,   /* field[1] = amount */
};
static const ProtobufCIntRange proto__account_amount__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__account_amount__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.AccountAmount",
  "AccountAmount",
  "Proto__AccountAmount",
  "proto",
  sizeof(Proto__AccountAmount),
  2,
  proto__account_amount__field_descriptors,
  proto__account_amount__field_indices_by_name,
  1,  proto__account_amount__number_ranges,
  (ProtobufCMessageInit) proto__account_amount__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__transfer_list__field_descriptors[1] =
{
  {
    "accountAmounts",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TransferList, n_accountamounts),
    offsetof(Proto__TransferList, accountamounts),
    &proto__account_amount__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__transfer_list__field_indices_by_name[] = {
  0,   /* field[0] = accountAmounts */
};
static const ProtobufCIntRange proto__transfer_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__transfer_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TransferList",
  "TransferList",
  "Proto__TransferList",
  "proto",
  sizeof(Proto__TransferList),
  1,
  proto__transfer_list__field_descriptors,
  proto__transfer_list__field_indices_by_name,
  1,  proto__transfer_list__number_ranges,
  (ProtobufCMessageInit) proto__transfer_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__crypto_transfer_transaction_body__field_descriptors[1] =
{
  {
    "transfers",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CryptoTransferTransactionBody, transfers),
    &proto__transfer_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto_transfer_transaction_body__field_indices_by_name[] = {
  0,   /* field[0] = transfers */
};
static const ProtobufCIntRange proto__crypto_transfer_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__crypto_transfer_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.CryptoTransferTransactionBody",
  "CryptoTransferTransactionBody",
  "Proto__CryptoTransferTransactionBody",
  "proto",
  sizeof(Proto__CryptoTransferTransactionBody),
  1,
  proto__crypto_transfer_transaction_body__field_descriptors,
  proto__crypto_transfer_transaction_body__field_indices_by_name,
  1,  proto__crypto_transfer_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__crypto_transfer_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
