/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Duration.proto */

#ifndef PROTOBUF_C_Duration_2eproto__INCLUDED
#define PROTOBUF_C_Duration_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Proto__Duration Proto__Duration;


/* --- enums --- */


/* --- messages --- */

/*
 *  The length of a period of time. This is an identical data structure to the protobuf Duration.proto (see the comments in https://github.com/google/protobuf/blob/master/src/google/protobuf/duration.proto) 
 */
struct  _Proto__Duration
{
  ProtobufCMessage base;
  /*
   * number of seconds
   */
  int64_t seconds;
};
#define PROTO__DURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__duration__descriptor) \
    , 0 }


/* Proto__Duration methods */
void   proto__duration__init
                     (Proto__Duration         *message);
size_t proto__duration__get_packed_size
                     (const Proto__Duration   *message);
size_t proto__duration__pack
                     (const Proto__Duration   *message,
                      uint8_t             *out);
size_t proto__duration__pack_to_buffer
                     (const Proto__Duration   *message,
                      ProtobufCBuffer     *buffer);
Proto__Duration *
       proto__duration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__duration__free_unpacked
                     (Proto__Duration *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__Duration_Closure)
                 (const Proto__Duration *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__duration__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Duration_2eproto__INCLUDED */
