/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ExchangeRate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ExchangeRate.pb-c.h"
void   proto__exchange_rate__init
                     (Proto__ExchangeRate         *message)
{
  static const Proto__ExchangeRate init_value = PROTO__EXCHANGE_RATE__INIT;
  *message = init_value;
}
size_t proto__exchange_rate__get_packed_size
                     (const Proto__ExchangeRate *message)
{
  assert(message->base.descriptor == &proto__exchange_rate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__exchange_rate__pack
                     (const Proto__ExchangeRate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__exchange_rate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__exchange_rate__pack_to_buffer
                     (const Proto__ExchangeRate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__exchange_rate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ExchangeRate *
       proto__exchange_rate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ExchangeRate *)
     protobuf_c_message_unpack (&proto__exchange_rate__descriptor,
                                allocator, len, data);
}
void   proto__exchange_rate__free_unpacked
                     (Proto__ExchangeRate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__exchange_rate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__exchange_rate_set__init
                     (Proto__ExchangeRateSet         *message)
{
  static const Proto__ExchangeRateSet init_value = PROTO__EXCHANGE_RATE_SET__INIT;
  *message = init_value;
}
size_t proto__exchange_rate_set__get_packed_size
                     (const Proto__ExchangeRateSet *message)
{
  assert(message->base.descriptor == &proto__exchange_rate_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__exchange_rate_set__pack
                     (const Proto__ExchangeRateSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__exchange_rate_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__exchange_rate_set__pack_to_buffer
                     (const Proto__ExchangeRateSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__exchange_rate_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ExchangeRateSet *
       proto__exchange_rate_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ExchangeRateSet *)
     protobuf_c_message_unpack (&proto__exchange_rate_set__descriptor,
                                allocator, len, data);
}
void   proto__exchange_rate_set__free_unpacked
                     (Proto__ExchangeRateSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__exchange_rate_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__exchange_rate__field_descriptors[3] =
{
  {
    "hbarEquiv",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ExchangeRate, hbarequiv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "centEquiv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ExchangeRate, centequiv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expirationTime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ExchangeRate, expirationtime),
    &proto__timestamp_seconds__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__exchange_rate__field_indices_by_name[] = {
  1,   /* field[1] = centEquiv */
  2,   /* field[2] = expirationTime */
  0,   /* field[0] = hbarEquiv */
};
static const ProtobufCIntRange proto__exchange_rate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__exchange_rate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ExchangeRate",
  "ExchangeRate",
  "Proto__ExchangeRate",
  "proto",
  sizeof(Proto__ExchangeRate),
  3,
  proto__exchange_rate__field_descriptors,
  proto__exchange_rate__field_indices_by_name,
  1,  proto__exchange_rate__number_ranges,
  (ProtobufCMessageInit) proto__exchange_rate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__exchange_rate_set__field_descriptors[2] =
{
  {
    "currentRate",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ExchangeRateSet, currentrate),
    &proto__exchange_rate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nextRate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ExchangeRateSet, nextrate),
    &proto__exchange_rate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__exchange_rate_set__field_indices_by_name[] = {
  0,   /* field[0] = currentRate */
  1,   /* field[1] = nextRate */
};
static const ProtobufCIntRange proto__exchange_rate_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__exchange_rate_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ExchangeRateSet",
  "ExchangeRateSet",
  "Proto__ExchangeRateSet",
  "proto",
  sizeof(Proto__ExchangeRateSet),
  2,
  proto__exchange_rate_set__field_descriptors,
  proto__exchange_rate_set__field_indices_by_name,
  1,  proto__exchange_rate_set__number_ranges,
  (ProtobufCMessageInit) proto__exchange_rate_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
