/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileAppend.proto */

#ifndef PROTOBUF_C_FileAppend_2eproto__INCLUDED
#define PROTOBUF_C_FileAppend_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"

typedef struct _Proto__FileAppendTransactionBody Proto__FileAppendTransactionBody;


/* --- enums --- */


/* --- messages --- */

/*
 * Append the given contents to the end of the file. If a file is too big to create with a single FileCreateTransaction, then it can be created with the first part of its contents, and then appended multiple times to create the entire file. 
 */
struct  _Proto__FileAppendTransactionBody
{
  ProtobufCMessage base;
  /*
   * The file ID of the file to which the bytes are appended to
   */
  Proto__FileID *fileid;
  /*
   * The bytes to append to the contents of the file
   */
  ProtobufCBinaryData contents;
};
#define PROTO__FILE_APPEND_TRANSACTION_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__file_append_transaction_body__descriptor) \
    , NULL, {0,NULL} }


/* Proto__FileAppendTransactionBody methods */
void   proto__file_append_transaction_body__init
                     (Proto__FileAppendTransactionBody         *message);
size_t proto__file_append_transaction_body__get_packed_size
                     (const Proto__FileAppendTransactionBody   *message);
size_t proto__file_append_transaction_body__pack
                     (const Proto__FileAppendTransactionBody   *message,
                      uint8_t             *out);
size_t proto__file_append_transaction_body__pack_to_buffer
                     (const Proto__FileAppendTransactionBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__FileAppendTransactionBody *
       proto__file_append_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__file_append_transaction_body__free_unpacked
                     (Proto__FileAppendTransactionBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__FileAppendTransactionBody_Closure)
                 (const Proto__FileAppendTransactionBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__file_append_transaction_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_FileAppend_2eproto__INCLUDED */
