/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileUpdate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FileUpdate.pb-c.h"
void   proto__file_update_transaction_body__init
                     (Proto__FileUpdateTransactionBody         *message)
{
  static const Proto__FileUpdateTransactionBody init_value = PROTO__FILE_UPDATE_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__file_update_transaction_body__get_packed_size
                     (const Proto__FileUpdateTransactionBody *message)
{
  assert(message->base.descriptor == &proto__file_update_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__file_update_transaction_body__pack
                     (const Proto__FileUpdateTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__file_update_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__file_update_transaction_body__pack_to_buffer
                     (const Proto__FileUpdateTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__file_update_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FileUpdateTransactionBody *
       proto__file_update_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FileUpdateTransactionBody *)
     protobuf_c_message_unpack (&proto__file_update_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__file_update_transaction_body__free_unpacked
                     (Proto__FileUpdateTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__file_update_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__file_update_transaction_body__field_descriptors[4] =
{
  {
    "fileID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileUpdateTransactionBody, fileid),
    &proto__file_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expirationTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileUpdateTransactionBody, expirationtime),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileUpdateTransactionBody, keys),
    &proto__key_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contents",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__FileUpdateTransactionBody, contents),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__file_update_transaction_body__field_indices_by_name[] = {
  3,   /* field[3] = contents */
  1,   /* field[1] = expirationTime */
  0,   /* field[0] = fileID */
  2,   /* field[2] = keys */
};
static const ProtobufCIntRange proto__file_update_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__file_update_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FileUpdateTransactionBody",
  "FileUpdateTransactionBody",
  "Proto__FileUpdateTransactionBody",
  "proto",
  sizeof(Proto__FileUpdateTransactionBody),
  4,
  proto__file_update_transaction_body__field_descriptors,
  proto__file_update_transaction_body__field_indices_by_name,
  1,  proto__file_update_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__file_update_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
