/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileGetInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FileGetInfo.pb-c.h"
void   proto__file_get_info_query__init
                     (Proto__FileGetInfoQuery         *message)
{
  static const Proto__FileGetInfoQuery init_value = PROTO__FILE_GET_INFO_QUERY__INIT;
  *message = init_value;
}
size_t proto__file_get_info_query__get_packed_size
                     (const Proto__FileGetInfoQuery *message)
{
  assert(message->base.descriptor == &proto__file_get_info_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__file_get_info_query__pack
                     (const Proto__FileGetInfoQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__file_get_info_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__file_get_info_query__pack_to_buffer
                     (const Proto__FileGetInfoQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__file_get_info_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FileGetInfoQuery *
       proto__file_get_info_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FileGetInfoQuery *)
     protobuf_c_message_unpack (&proto__file_get_info_query__descriptor,
                                allocator, len, data);
}
void   proto__file_get_info_query__free_unpacked
                     (Proto__FileGetInfoQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__file_get_info_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__file_get_info_response__file_info__init
                     (Proto__FileGetInfoResponse__FileInfo         *message)
{
  static const Proto__FileGetInfoResponse__FileInfo init_value = PROTO__FILE_GET_INFO_RESPONSE__FILE_INFO__INIT;
  *message = init_value;
}
void   proto__file_get_info_response__init
                     (Proto__FileGetInfoResponse         *message)
{
  static const Proto__FileGetInfoResponse init_value = PROTO__FILE_GET_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__file_get_info_response__get_packed_size
                     (const Proto__FileGetInfoResponse *message)
{
  assert(message->base.descriptor == &proto__file_get_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__file_get_info_response__pack
                     (const Proto__FileGetInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__file_get_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__file_get_info_response__pack_to_buffer
                     (const Proto__FileGetInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__file_get_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FileGetInfoResponse *
       proto__file_get_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FileGetInfoResponse *)
     protobuf_c_message_unpack (&proto__file_get_info_response__descriptor,
                                allocator, len, data);
}
void   proto__file_get_info_response__free_unpacked
                     (Proto__FileGetInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__file_get_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__file_get_info_query__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoQuery, fileid),
    &proto__file_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__file_get_info_query__field_indices_by_name[] = {
  1,   /* field[1] = fileID */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__file_get_info_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__file_get_info_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FileGetInfoQuery",
  "FileGetInfoQuery",
  "Proto__FileGetInfoQuery",
  "proto",
  sizeof(Proto__FileGetInfoQuery),
  2,
  proto__file_get_info_query__field_descriptors,
  proto__file_get_info_query__field_indices_by_name,
  1,  proto__file_get_info_query__number_ranges,
  (ProtobufCMessageInit) proto__file_get_info_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__file_get_info_response__file_info__field_descriptors[5] =
{
  {
    "fileID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse__FileInfo, fileid),
    &proto__file_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse__FileInfo, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expirationTime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse__FileInfo, expirationtime),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse__FileInfo, deleted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse__FileInfo, keys),
    &proto__key_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__file_get_info_response__file_info__field_indices_by_name[] = {
  3,   /* field[3] = deleted */
  2,   /* field[2] = expirationTime */
  0,   /* field[0] = fileID */
  4,   /* field[4] = keys */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange proto__file_get_info_response__file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor proto__file_get_info_response__file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FileGetInfoResponse.FileInfo",
  "FileInfo",
  "Proto__FileGetInfoResponse__FileInfo",
  "proto",
  sizeof(Proto__FileGetInfoResponse__FileInfo),
  5,
  proto__file_get_info_response__file_info__field_descriptors,
  proto__file_get_info_response__file_info__field_indices_by_name,
  1,  proto__file_get_info_response__file_info__number_ranges,
  (ProtobufCMessageInit) proto__file_get_info_response__file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__file_get_info_response__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileInfo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileGetInfoResponse, fileinfo),
    &proto__file_get_info_response__file_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__file_get_info_response__field_indices_by_name[] = {
  1,   /* field[1] = fileInfo */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__file_get_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__file_get_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FileGetInfoResponse",
  "FileGetInfoResponse",
  "Proto__FileGetInfoResponse",
  "proto",
  sizeof(Proto__FileGetInfoResponse),
  2,
  proto__file_get_info_response__field_descriptors,
  proto__file_get_info_response__field_indices_by_name,
  1,  proto__file_get_info_response__number_ranges,
  (ProtobufCMessageInit) proto__file_get_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
