/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileDelete.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FileDelete.pb-c.h"
void   proto__file_delete_transaction_body__init
                     (Proto__FileDeleteTransactionBody         *message)
{
  static const Proto__FileDeleteTransactionBody init_value = PROTO__FILE_DELETE_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__file_delete_transaction_body__get_packed_size
                     (const Proto__FileDeleteTransactionBody *message)
{
  assert(message->base.descriptor == &proto__file_delete_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__file_delete_transaction_body__pack
                     (const Proto__FileDeleteTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__file_delete_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__file_delete_transaction_body__pack_to_buffer
                     (const Proto__FileDeleteTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__file_delete_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FileDeleteTransactionBody *
       proto__file_delete_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FileDeleteTransactionBody *)
     protobuf_c_message_unpack (&proto__file_delete_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__file_delete_transaction_body__free_unpacked
                     (Proto__FileDeleteTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__file_delete_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__file_delete_transaction_body__field_descriptors[1] =
{
  {
    "fileID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FileDeleteTransactionBody, fileid),
    &proto__file_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__file_delete_transaction_body__field_indices_by_name[] = {
  0,   /* field[0] = fileID */
};
static const ProtobufCIntRange proto__file_delete_transaction_body__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__file_delete_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FileDeleteTransactionBody",
  "FileDeleteTransactionBody",
  "Proto__FileDeleteTransactionBody",
  "proto",
  sizeof(Proto__FileDeleteTransactionBody),
  1,
  proto__file_delete_transaction_body__field_descriptors,
  proto__file_delete_transaction_body__field_indices_by_name,
  1,  proto__file_delete_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__file_delete_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
