/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileService.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FileService.pb-c.h"
static const ProtobufCMethodDescriptor proto__file_service__method_descriptors[8] =
{
  { "createFile", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "updateFile", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "deleteFile", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "appendContent", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "getFileContent", &proto__query__descriptor, &proto__response__descriptor },
  { "getFileInfo", &proto__query__descriptor, &proto__response__descriptor },
  { "systemDelete", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "systemUndelete", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
};
const unsigned proto__file_service__method_indices_by_name[] = {
  3,        /* appendContent */
  0,        /* createFile */
  2,        /* deleteFile */
  4,        /* getFileContent */
  5,        /* getFileInfo */
  6,        /* systemDelete */
  7,        /* systemUndelete */
  1         /* updateFile */
};
const ProtobufCServiceDescriptor proto__file_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.FileService",
  "FileService",
  "Proto__FileService",
  "proto",
  8,
  proto__file_service__method_descriptors,
  proto__file_service__method_indices_by_name
};
void proto__file_service__create_file(ProtobufCService *service,
                                      const Proto__Transaction *input,
                                      Proto__TransactionResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__update_file(ProtobufCService *service,
                                      const Proto__Transaction *input,
                                      Proto__TransactionResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__delete_file(ProtobufCService *service,
                                      const Proto__Transaction *input,
                                      Proto__TransactionResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__append_content(ProtobufCService *service,
                                         const Proto__Transaction *input,
                                         Proto__TransactionResponse_Closure closure,
                                         void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__get_file_content(ProtobufCService *service,
                                           const Proto__Query *input,
                                           Proto__Response_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__get_file_info(ProtobufCService *service,
                                        const Proto__Query *input,
                                        Proto__Response_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__system_delete(ProtobufCService *service,
                                        const Proto__Transaction *input,
                                        Proto__TransactionResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__system_undelete(ProtobufCService *service,
                                          const Proto__Transaction *input,
                                          Proto__TransactionResponse_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &proto__file_service__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__file_service__init (Proto__FileService_Service *service,
                                Proto__FileService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__file_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
