/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FreezeService.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FreezeService.pb-c.h"
static const ProtobufCMethodDescriptor proto__freeze_service__method_descriptors[1] =
{
  { "freeze", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
};
const unsigned proto__freeze_service__method_indices_by_name[] = {
  0         /* freeze */
};
const ProtobufCServiceDescriptor proto__freeze_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.FreezeService",
  "FreezeService",
  "Proto__FreezeService",
  "proto",
  1,
  proto__freeze_service__method_descriptors,
  proto__freeze_service__method_indices_by_name
};
void proto__freeze_service__freeze(ProtobufCService *service,
                                   const Proto__Transaction *input,
                                   Proto__TransactionResponse_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &proto__freeze_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__freeze_service__init (Proto__FreezeService_Service *service,
                                  Proto__FreezeService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__freeze_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
