/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: GetBySolidityID.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "GetBySolidityID.pb-c.h"
void   proto__get_by_solidity_idquery__init
                     (Proto__GetBySolidityIDQuery         *message)
{
  static const Proto__GetBySolidityIDQuery init_value = PROTO__GET_BY_SOLIDITY_IDQUERY__INIT;
  *message = init_value;
}
size_t proto__get_by_solidity_idquery__get_packed_size
                     (const Proto__GetBySolidityIDQuery *message)
{
  assert(message->base.descriptor == &proto__get_by_solidity_idquery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__get_by_solidity_idquery__pack
                     (const Proto__GetBySolidityIDQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__get_by_solidity_idquery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__get_by_solidity_idquery__pack_to_buffer
                     (const Proto__GetBySolidityIDQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__get_by_solidity_idquery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__GetBySolidityIDQuery *
       proto__get_by_solidity_idquery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__GetBySolidityIDQuery *)
     protobuf_c_message_unpack (&proto__get_by_solidity_idquery__descriptor,
                                allocator, len, data);
}
void   proto__get_by_solidity_idquery__free_unpacked
                     (Proto__GetBySolidityIDQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__get_by_solidity_idquery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__get_by_solidity_idresponse__init
                     (Proto__GetBySolidityIDResponse         *message)
{
  static const Proto__GetBySolidityIDResponse init_value = PROTO__GET_BY_SOLIDITY_IDRESPONSE__INIT;
  *message = init_value;
}
size_t proto__get_by_solidity_idresponse__get_packed_size
                     (const Proto__GetBySolidityIDResponse *message)
{
  assert(message->base.descriptor == &proto__get_by_solidity_idresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__get_by_solidity_idresponse__pack
                     (const Proto__GetBySolidityIDResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__get_by_solidity_idresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__get_by_solidity_idresponse__pack_to_buffer
                     (const Proto__GetBySolidityIDResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__get_by_solidity_idresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__GetBySolidityIDResponse *
       proto__get_by_solidity_idresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__GetBySolidityIDResponse *)
     protobuf_c_message_unpack (&proto__get_by_solidity_idresponse__descriptor,
                                allocator, len, data);
}
void   proto__get_by_solidity_idresponse__free_unpacked
                     (Proto__GetBySolidityIDResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__get_by_solidity_idresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__get_by_solidity_idquery__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__GetBySolidityIDQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solidityID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__GetBySolidityIDQuery, solidityid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__get_by_solidity_idquery__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = solidityID */
};
static const ProtobufCIntRange proto__get_by_solidity_idquery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__get_by_solidity_idquery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.GetBySolidityIDQuery",
  "GetBySolidityIDQuery",
  "Proto__GetBySolidityIDQuery",
  "proto",
  sizeof(Proto__GetBySolidityIDQuery),
  2,
  proto__get_by_solidity_idquery__field_descriptors,
  proto__get_by_solidity_idquery__field_indices_by_name,
  1,  proto__get_by_solidity_idquery__number_ranges,
  (ProtobufCMessageInit) proto__get_by_solidity_idquery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__get_by_solidity_idresponse__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__GetBySolidityIDResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accountID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__GetBySolidityIDResponse, accountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileID",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__GetBySolidityIDResponse, fileid),
    &proto__file_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contractID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__GetBySolidityIDResponse, contractid),
    &proto__contract_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__get_by_solidity_idresponse__field_indices_by_name[] = {
  1,   /* field[1] = accountID */
  3,   /* field[3] = contractID */
  2,   /* field[2] = fileID */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__get_by_solidity_idresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__get_by_solidity_idresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.GetBySolidityIDResponse",
  "GetBySolidityIDResponse",
  "Proto__GetBySolidityIDResponse",
  "proto",
  sizeof(Proto__GetBySolidityIDResponse),
  4,
  proto__get_by_solidity_idresponse__field_descriptors,
  proto__get_by_solidity_idresponse__field_indices_by_name,
  1,  proto__get_by_solidity_idresponse__number_ranges,
  (ProtobufCMessageInit) proto__get_by_solidity_idresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
