/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SystemUndelete.proto */

#ifndef PROTOBUF_C_SystemUndelete_2eproto__INCLUDED
#define PROTOBUF_C_SystemUndelete_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"

typedef struct _Proto__SystemUndeleteTransactionBody Proto__SystemUndeleteTransactionBody;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  PROTO__SYSTEM_UNDELETE_TRANSACTION_BODY__ID__NOT_SET = 0,
  PROTO__SYSTEM_UNDELETE_TRANSACTION_BODY__ID_FILE_ID = 1,
  PROTO__SYSTEM_UNDELETE_TRANSACTION_BODY__ID_CONTRACT_ID = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__SYSTEM_UNDELETE_TRANSACTION_BODY__ID)
} Proto__SystemUndeleteTransactionBody__IdCase;

/*
 * Undelete a file or smart contract that was deleted by AdminDelete - can only be done with a Hedera admin multisig. When it is deleted, it immediately disappears from the system as seen by the user, but is still stored internally until the expiration time, at which time it is truly and permanently deleted. Until that time, it can be undeleted by the Hedera admin multisig. When a smart contract is deleted, the cryptocurrency account within it continues to exist, and is not affected by the expiration time here. 
 */
struct  _Proto__SystemUndeleteTransactionBody
{
  ProtobufCMessage base;
  Proto__SystemUndeleteTransactionBody__IdCase id_case;
  union {
    /*
     * The file ID to undelete, in the format used in transactions
     */
    Proto__FileID *fileid;
    /*
     * The contract ID instance to undelete, in the format used in transactions
     */
    Proto__ContractID *contractid;
  };
};
#define PROTO__SYSTEM_UNDELETE_TRANSACTION_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__system_undelete_transaction_body__descriptor) \
    , PROTO__SYSTEM_UNDELETE_TRANSACTION_BODY__ID__NOT_SET, {0} }


/* Proto__SystemUndeleteTransactionBody methods */
void   proto__system_undelete_transaction_body__init
                     (Proto__SystemUndeleteTransactionBody         *message);
size_t proto__system_undelete_transaction_body__get_packed_size
                     (const Proto__SystemUndeleteTransactionBody   *message);
size_t proto__system_undelete_transaction_body__pack
                     (const Proto__SystemUndeleteTransactionBody   *message,
                      uint8_t             *out);
size_t proto__system_undelete_transaction_body__pack_to_buffer
                     (const Proto__SystemUndeleteTransactionBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__SystemUndeleteTransactionBody *
       proto__system_undelete_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__system_undelete_transaction_body__free_unpacked
                     (Proto__SystemUndeleteTransactionBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__SystemUndeleteTransactionBody_Closure)
                 (const Proto__SystemUndeleteTransactionBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__system_undelete_transaction_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SystemUndelete_2eproto__INCLUDED */
