/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TransactionRecord.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TransactionRecord.pb-c.h"
void   proto__transaction_record__init
                     (Proto__TransactionRecord         *message)
{
  static const Proto__TransactionRecord init_value = PROTO__TRANSACTION_RECORD__INIT;
  *message = init_value;
}
size_t proto__transaction_record__get_packed_size
                     (const Proto__TransactionRecord *message)
{
  assert(message->base.descriptor == &proto__transaction_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__transaction_record__pack
                     (const Proto__TransactionRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__transaction_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__transaction_record__pack_to_buffer
                     (const Proto__TransactionRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__transaction_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TransactionRecord *
       proto__transaction_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TransactionRecord *)
     protobuf_c_message_unpack (&proto__transaction_record__descriptor,
                                allocator, len, data);
}
void   proto__transaction_record__free_unpacked
                     (Proto__TransactionRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__transaction_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__transaction_record__field_descriptors[9] =
{
  {
    "receipt",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, receipt),
    &proto__transaction_receipt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionHash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, transactionhash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "consensusTimestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, consensustimestamp),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, transactionid),
    &proto__transaction_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memo",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, memo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionFee",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, transactionfee),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contractCallResult",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TransactionRecord, body_case),
    offsetof(Proto__TransactionRecord, contractcallresult),
    &proto__contract_function_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contractCreateResult",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TransactionRecord, body_case),
    offsetof(Proto__TransactionRecord, contractcreateresult),
    &proto__contract_function_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transferList",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionRecord, transferlist),
    &proto__transfer_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__transaction_record__field_indices_by_name[] = {
  2,   /* field[2] = consensusTimestamp */
  6,   /* field[6] = contractCallResult */
  7,   /* field[7] = contractCreateResult */
  4,   /* field[4] = memo */
  0,   /* field[0] = receipt */
  5,   /* field[5] = transactionFee */
  1,   /* field[1] = transactionHash */
  3,   /* field[3] = transactionID */
  8,   /* field[8] = transferList */
};
static const ProtobufCIntRange proto__transaction_record__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 8 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor proto__transaction_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TransactionRecord",
  "TransactionRecord",
  "Proto__TransactionRecord",
  "proto",
  sizeof(Proto__TransactionRecord),
  9,
  proto__transaction_record__field_descriptors,
  proto__transaction_record__field_indices_by_name,
  2,  proto__transaction_record__number_ranges,
  (ProtobufCMessageInit) proto__transaction_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
