/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TransactionResponse.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TransactionResponse.pb-c.h"
void   proto__transaction_response__init
                     (Proto__TransactionResponse         *message)
{
  static const Proto__TransactionResponse init_value = PROTO__TRANSACTION_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__transaction_response__get_packed_size
                     (const Proto__TransactionResponse *message)
{
  assert(message->base.descriptor == &proto__transaction_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__transaction_response__pack
                     (const Proto__TransactionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__transaction_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__transaction_response__pack_to_buffer
                     (const Proto__TransactionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__transaction_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TransactionResponse *
       proto__transaction_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TransactionResponse *)
     protobuf_c_message_unpack (&proto__transaction_response__descriptor,
                                allocator, len, data);
}
void   proto__transaction_response__free_unpacked
                     (Proto__TransactionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__transaction_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__transaction_response__field_descriptors[1] =
{
  {
    "nodeTransactionPrecheckCode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionResponse, nodetransactionprecheckcode),
    &proto__response_code_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__transaction_response__field_indices_by_name[] = {
  0,   /* field[0] = nodeTransactionPrecheckCode */
};
static const ProtobufCIntRange proto__transaction_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__transaction_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TransactionResponse",
  "TransactionResponse",
  "Proto__TransactionResponse",
  "proto",
  sizeof(Proto__TransactionResponse),
  1,
  proto__transaction_response__field_descriptors,
  proto__transaction_response__field_indices_by_name,
  1,  proto__transaction_response__number_ranges,
  (ProtobufCMessageInit) proto__transaction_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
