/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TransactionGetReceipt.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TransactionGetReceipt.pb-c.h"
void   proto__transaction_get_receipt_query__init
                     (Proto__TransactionGetReceiptQuery         *message)
{
  static const Proto__TransactionGetReceiptQuery init_value = PROTO__TRANSACTION_GET_RECEIPT_QUERY__INIT;
  *message = init_value;
}
size_t proto__transaction_get_receipt_query__get_packed_size
                     (const Proto__TransactionGetReceiptQuery *message)
{
  assert(message->base.descriptor == &proto__transaction_get_receipt_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__transaction_get_receipt_query__pack
                     (const Proto__TransactionGetReceiptQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__transaction_get_receipt_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__transaction_get_receipt_query__pack_to_buffer
                     (const Proto__TransactionGetReceiptQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__transaction_get_receipt_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TransactionGetReceiptQuery *
       proto__transaction_get_receipt_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TransactionGetReceiptQuery *)
     protobuf_c_message_unpack (&proto__transaction_get_receipt_query__descriptor,
                                allocator, len, data);
}
void   proto__transaction_get_receipt_query__free_unpacked
                     (Proto__TransactionGetReceiptQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__transaction_get_receipt_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__transaction_get_receipt_response__init
                     (Proto__TransactionGetReceiptResponse         *message)
{
  static const Proto__TransactionGetReceiptResponse init_value = PROTO__TRANSACTION_GET_RECEIPT_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__transaction_get_receipt_response__get_packed_size
                     (const Proto__TransactionGetReceiptResponse *message)
{
  assert(message->base.descriptor == &proto__transaction_get_receipt_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__transaction_get_receipt_response__pack
                     (const Proto__TransactionGetReceiptResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__transaction_get_receipt_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__transaction_get_receipt_response__pack_to_buffer
                     (const Proto__TransactionGetReceiptResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__transaction_get_receipt_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TransactionGetReceiptResponse *
       proto__transaction_get_receipt_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TransactionGetReceiptResponse *)
     protobuf_c_message_unpack (&proto__transaction_get_receipt_response__descriptor,
                                allocator, len, data);
}
void   proto__transaction_get_receipt_response__free_unpacked
                     (Proto__TransactionGetReceiptResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__transaction_get_receipt_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__transaction_get_receipt_query__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionGetReceiptQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionGetReceiptQuery, transactionid),
    &proto__transaction_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__transaction_get_receipt_query__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = transactionID */
};
static const ProtobufCIntRange proto__transaction_get_receipt_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__transaction_get_receipt_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TransactionGetReceiptQuery",
  "TransactionGetReceiptQuery",
  "Proto__TransactionGetReceiptQuery",
  "proto",
  sizeof(Proto__TransactionGetReceiptQuery),
  2,
  proto__transaction_get_receipt_query__field_descriptors,
  proto__transaction_get_receipt_query__field_indices_by_name,
  1,  proto__transaction_get_receipt_query__number_ranges,
  (ProtobufCMessageInit) proto__transaction_get_receipt_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__transaction_get_receipt_response__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionGetReceiptResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receipt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TransactionGetReceiptResponse, receipt),
    &proto__transaction_receipt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__transaction_get_receipt_response__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = receipt */
};
static const ProtobufCIntRange proto__transaction_get_receipt_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__transaction_get_receipt_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TransactionGetReceiptResponse",
  "TransactionGetReceiptResponse",
  "Proto__TransactionGetReceiptResponse",
  "proto",
  sizeof(Proto__TransactionGetReceiptResponse),
  2,
  proto__transaction_get_receipt_response__field_descriptors,
  proto__transaction_get_receipt_response__field_indices_by_name,
  1,  proto__transaction_get_receipt_response__number_ranges,
  (ProtobufCMessageInit) proto__transaction_get_receipt_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
