/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Transaction.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Transaction.pb-c.h"
void   proto__transaction__init
                     (Proto__Transaction         *message)
{
  static const Proto__Transaction init_value = PROTO__TRANSACTION__INIT;
  *message = init_value;
}
size_t proto__transaction__get_packed_size
                     (const Proto__Transaction *message)
{
  assert(message->base.descriptor == &proto__transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__transaction__pack
                     (const Proto__Transaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__transaction__pack_to_buffer
                     (const Proto__Transaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Transaction *
       proto__transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Transaction *)
     protobuf_c_message_unpack (&proto__transaction__descriptor,
                                allocator, len, data);
}
void   proto__transaction__free_unpacked
                     (Proto__Transaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__transaction__field_descriptors[4] =
{
  {
    "body",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__Transaction, body_data_case),
    offsetof(Proto__Transaction, body),
    &proto__transaction_body__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigs",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__Transaction, sigs),
    &proto__signature_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigMap",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__Transaction, sigmap),
    &proto__signature_map__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bodyBytes",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Proto__Transaction, body_data_case),
    offsetof(Proto__Transaction, bodybytes),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__transaction__field_indices_by_name[] = {
  0,   /* field[0] = body */
  3,   /* field[3] = bodyBytes */
  2,   /* field[2] = sigMap */
  1,   /* field[1] = sigs */
};
static const ProtobufCIntRange proto__transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.Transaction",
  "Transaction",
  "Proto__Transaction",
  "proto",
  sizeof(Proto__Transaction),
  4,
  proto__transaction__field_descriptors,
  proto__transaction__field_indices_by_name,
  1,  proto__transaction__number_ranges,
  (ProtobufCMessageInit) proto__transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
