package com.breadwallet.crypto.libcrypto.bitcoin;

public interface BRWalletManagerEventType {

    int BITCOIN_WALLET_MANAGER_CREATED = 0;
    int BITCOIN_WALLET_MANAGER_CONNECTED = 1;
    int BITCOIN_WALLET_MANAGER_DISCONNECTED = 2;
    int BITCOIN_WALLET_MANAGER_SYNC_STARTED = 3;
    int BITCOIN_WALLET_MANAGER_SYNC_STOPPED = 4;
    int BITCOIN_WALLET_MANAGER_BLOCK_HEIGHT_UPDATED = 5;
}
